import type { LessonCard } from './lessons';

/**
 * The dedicated CODING tracks (assemble/querybuild) — separated from the on-call/diagnosis
 * units. A querybuild is FRONT-LOADED as node 1 so "coding" is reachable immediately.
 * Verified Python/SQL. Merged into LESSON_SEED by lessons.ts.
 */
export const CODING_LESSONS: LessonCard[] = [
  // ───────────────────────── Python Coding ─────────────────────────
  {
    track: 'python-drills',
    id: 'L-pyc-build-groupby',
    kind: 'querybuild',
    tk: 'kafka',
    tool: 'pandas',
    tag: 'Build the transform · Mid',
    q: 'Total revenue per region, highest first. Build the pandas transform.',
    querybuild: {
      setup: {
        schema: '# df(region, amount) — one row per order',
        rows: ['US -> 100, US -> 50, EU -> 80'],
        expected: 'US 150, EU 80',
      },
      hints: ['group on the key, sum the measure, sort desc.', 'reset_index() tidies the grouped Series.'],
      beats: [
        {
          kind: 'infer',
          prompt: 'Vectorized way to total a measure per key?',
          opts: [
            { t: 'df.groupby("region")["amount"].sum()', ok: true },
            { t: 'for r in df.iterrows(): totals[...] += ...', ok: false, why: 'A row loop — 10-100x slower, not idiomatic.' },
            { t: 'df["amount"].sum()', ok: false, why: 'Totals everything, ignores region.' },
          ],
          why: 'groupby + a reducing agg is the vectorized idiom; iterrows is the junior trap.',
        },
      ],
      assemble: {
        bank: [
          { t: 'df.groupby("region")', pos: 0 },
          { t: '["amount"].sum()', pos: 1 },
          { t: '.sort_values(ascending=False)', pos: 2 },
          { t: '.reset_index()', pos: 3 },
          { t: 'for _, row in df.iterrows():', pos: -1 },
          { t: '.apply(lambda x: x.sum())', pos: -1 },
        ],
      },
      acceptedSeqs: [[0, 1, 2, 3]],
      webx: {
        blurb: 'You built it from parts. Now type it and Run it on a real DataFrame, then Submit for an AI-graded read.',
        problemId: 'py-revenue-per-region',
      },
    },
    fj: '"Loop with iterrows and a dict."',
    fs: '"groupby-sum-sort, vectorized — never iterrows for aggregation."',
  },
  {
    track: 'python-drills',
    id: 'L-pyc-evidence-mutable-default',
    kind: 'evidence',
    tk: 'kafka',
    tool: 'Python',
    tag: 'Spot the bug · Mid',
    q: 'This helper accumulates rows across unrelated calls. Tap the line that causes it.',
    evidence: {
      panel: {
        kind: 'code',
        lang: 'python',
        lines: ['def collect(row, acc=[]):', '    acc.append(row)', '    return acc', '', 'collect(1)   # [1]', 'collect(2)   # [1, 2]  leaks'],
      },
      tells: [0],
      cause: [
        { t: 'Mutable default acc=[] is created once at def-time and shared', ok: true },
        { t: 'append mutates in place so copy first', ok: false, why: 'append is fine; the shared default is the bug.' },
        { t: 'Missing return inside a loop', ok: false, why: 'No loop, and return is present.' },
      ],
      why: 'Default args evaluate once at definition; the same list is reused. Use acc=None then acc = acc if acc is not None else [].',
    },
    fj: '"Each call gets a fresh list."',
    fs: '"Mutable defaults persist — None sentinel, build inside."',
  },
  {
    track: 'python-drills',
    id: 'L-pyc-choice-dedup-latest',
    kind: 'choice',
    tk: 'kafka',
    tool: 'pandas',
    tag: 'Pick the fix · Sr',
    strict: true,
    q: 'Keep the HIGHEST-score row per user_id from unsorted input. Which is correct AND order-safe?',
    lang: 'python',
    lines: ['# df: user_id, score (arbitrary order)', '# want the max-score row per user'],
    opts: [
      { t: 'df.loc[df.groupby("user_id")["score"].idxmax()]', ok: true },
      { t: 'df.drop_duplicates("user_id", keep="last")', ok: false, why: 'Keeps the last ROW by position, not the max — wrong unless pre-sorted.' },
      { t: 'df.drop_duplicates("user_id")', ok: false, why: 'Keeps the first occurrence — ignores score.' },
      { t: 'df.groupby("user_id").max()', ok: false, why: 'Maxes each column independently — scrambles which row each value is from.' },
    ],
    why: 'idxmax() returns the index of the max score per group; .loc pulls those exact rows. drop_duplicates is position-based.',
    fj: '"drop_duplicates keep=last."',
    fs: '"groupby().idxmax() + .loc — order-independent, keeps the whole row."',
  },
  {
    track: 'python-drills',
    id: 'L-pyc-order-pipeline',
    kind: 'order',
    tk: 'kafka',
    tool: 'pandas',
    tag: 'Pipeline order · Mid',
    q: 'Order these ETL steps so the dedupe and write are correct.',
    order: {
      rows: [
        'df = pd.read_parquet("raw")',
        'df = df.dropna(subset=["id"])',
        'df = df.drop_duplicates("id", keep="last")',
        'df = df.sort_values("ts")',
        'df.to_parquet("clean")',
      ],
      accepted: [[0, 1, 3, 2, 4]],
      mono: true,
    },
    why: 'Read -> drop null keys -> sort by ts so keep="last" means newest -> dedupe -> write. Dedup before sorting would keep an arbitrary row.',
    fj: '"Order does not matter."',
    fs: '"Sort before keep=last so latest wins, then write."',
  },
  {
    track: 'python-drills',
    id: 'L-pyc-match-comprehension',
    kind: 'match',
    tk: 'kafka',
    tool: 'Python',
    tag: 'Assemble · Mid',
    q: 'Assemble a list comprehension: squares of the even numbers in xs. Tap tokens in order.',
    match: {
      bank: [
        { t: '[x * x', pos: 0 },
        { t: 'for x in xs', pos: 1 },
        { t: 'if x % 2 == 0', pos: 2 },
        { t: ']', pos: 3 },
        { t: 'if x % 2 == 1', pos: -1 },
        { t: 'for xs in x', pos: -1 },
      ],
      acceptedSeqs: [[0, 1, 2, 3]],
      why: 'Expression first, then the for-clause, then the filter: [x*x for x in xs if x % 2 == 0].',
    },
    fj: '"Filter goes before the for."',
    fs: '"expr -> for -> if, all inside the brackets."',
  },
  {
    track: 'python-drills',
    id: 'L-pyc-choice-generator',
    kind: 'choice',
    tk: 'kafka',
    tool: 'Python',
    tag: 'Predict output · Mid',
    strict: true,
    q: 'What does this print?',
    lang: 'python',
    lines: ['g = (x * 2 for x in range(3))', 'print(next(g))', 'print(list(g))'],
    opts: [
      { t: '0 then [2, 4]', ok: true },
      { t: '0 then [0, 2, 4]', ok: false, why: 'next() already consumed 0 — generators are stateful, not restartable.' },
      { t: '[0,2,4] then []', ok: false, why: 'next() yields one value (0), not the whole list.' },
      { t: 'TypeError', ok: false, why: 'A generator expression is valid; next() and list() both work.' },
    ],
    why: 'A generator is a lazy, one-pass iterator. next(g) yields 0; list(g) drains the rest -> [2, 4].',
    fj: '"list(g) restarts from the beginning."',
    fs: '"Generators are single-pass and stateful — consumed items are gone."',
  },

  // ───────────────────────── SQL Coding ─────────────────────────
  {
    track: 'sql-coding',
    id: 'L-sqlc-build-running-total',
    kind: 'querybuild',
    tk: 'sql',
    tool: 'SQL',
    tag: 'Window · Mid',
    q: 'Running total of amount per user, ordered by day. Build it.',
    querybuild: {
      setup: {
        schema: '# txns(user_id, day, amount)',
        rows: ['1, D1, 10', '1, D2, 5', '1, D3, 20'],
        expected: '10, 15, 35',
      },
      hints: ['a cumulative sum is SUM(...) OVER (... ORDER BY ...).', 'partition by user so totals reset; order by day in the window.'],
      beats: [
        {
          kind: 'infer',
          prompt: 'What makes SUM cumulative instead of a grand total?',
          opts: [
            { t: 'OVER (... ORDER BY day) — the default running frame', ok: true },
            { t: 'GROUP BY user_id, day', ok: false, why: 'Collapses rows; you need one running value per row.' },
            { t: 'SUM(amount) with no window', ok: false, why: 'A single grand total, not a per-row cumulative.' },
          ],
          why: 'ORDER BY inside OVER gives UNBOUNDED PRECEDING -> CURRENT ROW = a running sum.',
        },
      ],
      assemble: {
        bank: [
          { t: 'SELECT user_id, day,', pos: 0 },
          { t: 'SUM(amount) OVER (', pos: 1 },
          { t: 'PARTITION BY user_id ORDER BY day', pos: 2 },
          { t: ') AS running_total', pos: 3 },
          { t: 'FROM txns', pos: 4 },
          { t: 'GROUP BY user_id, day', pos: -1 },
        ],
      },
      acceptedSeqs: [[0, 1, 2, 3, 4]],
      webx: { blurb: 'You assembled it. Now type & Run it against live Postgres and Submit for an AI-graded read.', problemId: 'sql-running-total' },
    },
    fj: '"GROUP BY day and add them up."',
    fs: '"SUM() OVER (PARTITION BY user ORDER BY day) — windowed running total."',
  },
  {
    track: 'sql-coding',
    id: 'L-sqlc-build-dedup-rownumber',
    kind: 'querybuild',
    tk: 'sql',
    tool: 'SQL',
    tag: 'Dedup · Sr',
    q: 'Keep only the latest row per user_id from a table with duplicates. Build it.',
    querybuild: {
      setup: {
        schema: '# events(user_id, updated_at, status)',
        rows: ['1, T1, new', '1, T2, paid', '2, T1, new'],
        expected: '(1, paid), (2, new)',
      },
      hints: ['number rows per user newest-first, keep #1.', 'ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY updated_at DESC).'],
      beats: [
        {
          kind: 'infer',
          prompt: 'Which window function keeps exactly one row per user?',
          opts: [
            { t: 'ROW_NUMBER() — unique sequence, rn=1 is one row', ok: true },
            { t: 'RANK() — ties share rank 1, can keep duplicates', ok: false, why: 'On a tie you keep >1 row; ROW_NUMBER is exactly one.' },
            { t: 'DISTINCT user_id', ok: false, why: 'Loses status — you cannot recover the other columns.' },
          ],
          why: 'ROW_NUMBER assigns 1,2,3 with no ties, so rn=1 is the single latest row.',
        },
      ],
      assemble: {
        bank: [
          { t: 'WITH ranked AS (', pos: 0 },
          { t: 'SELECT *, ROW_NUMBER() OVER (', pos: 1 },
          { t: 'PARTITION BY user_id ORDER BY updated_at DESC', pos: 2 },
          { t: ') AS rn FROM events)', pos: 3 },
          { t: 'SELECT user_id, status FROM ranked WHERE rn = 1', pos: 4 },
          { t: 'SELECT DISTINCT user_id FROM events', pos: -1 },
        ],
      },
      acceptedSeqs: [[0, 1, 2, 3, 4]],
      webx: { blurb: 'Now type & Run the real dedup against live Postgres and get AI-graded follow-ups.', problemId: 'sql-dedup-latest' },
    },
    fj: '"SELECT DISTINCT user_id."',
    fs: '"ROW_NUMBER() partitioned by key, newest first, keep rn = 1."',
  },
  {
    track: 'sql-coding',
    id: 'L-sqlc-evidence-notin-null',
    kind: 'evidence',
    tk: 'sql',
    tool: 'SQL',
    tag: 'Spot the bug · Mid',
    q: 'One line here silently returns zero rows. Tap it.',
    evidence: {
      panel: { kind: 'code', lang: 'sql', lines: ['SELECT o.order_id', 'FROM orders o', 'WHERE o.user_id NOT IN (', '  SELECT user_id', '  FROM blacklist', ');'] },
      tells: [2],
      cause: [
        { t: 'NOT IN + a NULL in the subquery -> every row UNKNOWN -> 0 rows', ok: true },
        { t: 'Missing GROUP BY', ok: false, why: 'No aggregate here.' },
        { t: 'orders needs an index', ok: false, why: 'An index changes speed, not the empty result.' },
      ],
      why: 'A single NULL in blacklist.user_id makes every row UNKNOWN under NOT IN -> nothing returns. Use NOT EXISTS or filter IS NOT NULL.',
    },
    fj: '"NOT IN reads cleaner."',
    fs: '"NOT IN + NULLs = silent empty set — reach for NOT EXISTS."',
  },
  {
    track: 'sql-coding',
    id: 'L-sqlc-order-exec',
    kind: 'order',
    tk: 'sql',
    tool: 'SQL',
    tag: 'Execution order · Mid',
    q: 'Put these in the order the engine actually runs them.',
    order: {
      rows: ['SELECT customer_id, SUM(amount)', "WHERE created_at >= '2026-01-01'", 'FROM orders o', 'HAVING COUNT(*) > 5', 'GROUP BY customer_id'],
      accepted: [[2, 1, 4, 3, 0]],
      mono: true,
    },
    why: 'FROM -> WHERE -> GROUP BY -> HAVING -> SELECT. That is why a SELECT alias is not visible in WHERE.',
    fj: '"It runs top to bottom."',
    fs: '"Logical order != written order — FROM/WHERE first, SELECT almost last."',
  },
  {
    track: 'sql-coding',
    id: 'L-sqlc-build-division',
    kind: 'querybuild',
    tk: 'sql',
    tool: 'SQL',
    tag: 'Relational division · Sr',
    q: 'List candidates who have ALL three required skills — Python, Tableau, PostgreSQL.',
    querybuild: {
      setup: {
        schema: '# candidates(candidate_id, skill) — one row per skill',
        rows: ['123 -> Python, Tableau, PostgreSQL', '234 -> R, PowerBI', '345 -> Python, Tableau'],
        expected: '123',
      },
      hints: ['"has all of a set" is relational division.', 'filter to the 3 skills, GROUP BY candidate, HAVING COUNT(*) = 3.'],
      beats: [
        {
          kind: 'infer',
          prompt: 'How do you say "has ALL three"?',
          opts: [
            { t: 'Filter to the 3 skills, group by candidate, COUNT(*) = 3', ok: true },
            { t: "WHERE skill='Python' AND skill='Tableau' AND skill='PostgreSQL'", ok: false, why: 'A row holds one skill -> always false -> 0 rows.' },
            { t: 'Three queries, intersect by hand', ok: false, why: 'Relational division is one clean query.' },
          ],
          why: '"Has all of a set" = filter to the set, group, count = set size.',
        },
      ],
      assemble: {
        bank: [
          { t: 'SELECT candidate_id', pos: 0 },
          { t: 'FROM candidates', pos: 1 },
          { t: "WHERE skill IN ('Python','Tableau','PostgreSQL')", pos: 2 },
          { t: 'GROUP BY candidate_id', pos: 3 },
          { t: 'HAVING COUNT(*) = 3', pos: 4 },
          { t: 'HAVING COUNT(*) > 0', pos: -1 },
        ],
      },
      acceptedSeqs: [[0, 1, 2, 3, 4]],
      webx: { blurb: 'You built it from parts. Now write & Run it against live Postgres, Submit for an AI-graded read.', problemId: 'sql-candidates-all-skills' },
    },
    fj: '"AND the three skills in WHERE."',
    fs: '"Relational division — filter to the set, group, HAVING COUNT(*) = set size."',
  },
  {
    track: 'sql-coding',
    id: 'L-sqlc-match-not-exists',
    kind: 'match',
    tk: 'sql',
    tool: 'SQL',
    tag: 'Anti-join · Sr',
    q: 'Rebuild the blacklist filter as a NULL-safe anti-join. Tap tokens in order.',
    match: {
      bank: [
        { t: 'WHERE NOT EXISTS (', pos: 0 },
        { t: 'SELECT 1 FROM blacklist b', pos: 1 },
        { t: 'WHERE b.user_id = o.user_id', pos: 2 },
        { t: ')', pos: 3 },
        { t: 'NOT IN (', pos: -1 },
        { t: 'IS NULL', pos: -1 },
      ],
      acceptedSeqs: [[0, 1, 2, 3]],
      why: 'NOT EXISTS short-circuits per row and is immune to NULLs in the subquery — the default for "rows in A not matched in B".',
    },
    fj: '"NOT IN, obviously."',
    fs: '"NOT EXISTS — NULL-safe and usually a better plan."',
  },
];
