/**
 * Home / lock-screen WIDGET + Live Activity data provider (plan #18).
 *
 * This module is the JS half of the feature: a typed, pure-ish data provider
 * (`computeWidgetData`) plus a guarded native bridge (`pushWidgetUpdate`) that
 * NO-OPS anywhere the native widget extension isn't installed (Expo Go, web,
 * Android-without-glance, and any dev build that hasn't run the config plugin).
 *
 * The actual iOS widget is a Swift WidgetKit target generated by a config
 * plugin at prebuild time — see WIDGET_SETUP.md. There is no native widget code
 * in a managed/Expo-Go run, so EVERYTHING here must degrade to a silent no-op
 * when the bridge is absent. Never throw from this file.
 *
 * Data flow:
 *   store state + bundled content  ->  computeWidgetData()  ->  WidgetData
 *   WidgetData  ->  pushWidgetUpdate()  ->  (App Group shared store) -> Swift widget
 */

import { dailyPoolForRole, findCardById, type SessionCard } from './content';
import type { CardState } from './srs';

// ── Types ───────────────────────────────────────────────────────────────────

/** Everything the iOS widget + Live Activity surfaces need, in one flat payload. */
export interface WidgetData {
  /** Current daily streak (days). */
  streak: number;
  /** Cards due for review right now (SRS due <= now), capped for display. */
  dueCount: number;
  /** A short, glanceable "card of the day" prompt for the medium widget. */
  cardOfTheDay: { id: string; tool: string; q: string } | null;
  /** Days until the user's target interview, or null if none set. */
  interviewDaysLeft: number | null;
  /** Daily goal + progress toward it (drives the Live Activity ring). */
  goal: number;
  cardsToday: number;
  /** When this snapshot was computed (epoch ms) — lets the widget show staleness. */
  updatedAt: number;
}

/** The minimal slice of store state this provider reads. Kept structural so the
 *  caller can pass `useStore.getState()` directly without a new dependency. */
export interface WidgetStoreSlice {
  role: string;
  streak: number;
  progress: Record<string, CardState>;
  interviewIn: number | null;
  dailyGoal: number;
  cardsToday: number;
  savedIds?: string[];
}

// ── Pure computation ──────────────────────────────────────────────────────────

const MAX_DUE_DISPLAY = 99;

/** Truncate a question to a glanceable length for the small widget face. */
function clip(s: string, n = 90): string {
  const t = s.trim().replace(/\s+/g, ' ');
  return t.length > n ? t.slice(0, n - 1).trimEnd() + '…' : t;
}

/** Count cards whose SRS state is due (due <= now). Unseen cards are NOT counted
 *  as due — the widget mirrors "reviews waiting", not "new content available". */
function countDue(progress: Record<string, CardState>, now: number): number {
  let n = 0;
  for (const id in progress) {
    const st = progress[id];
    if (st && st.reps > 0 && st.due <= now) {
      n += 1;
      if (n >= MAX_DUE_DISPLAY) break;
    }
  }
  return n;
}

/**
 * Pick a stable "card of the day": deterministic per calendar day + role so the
 * widget face doesn't flicker between refreshes within a day. Prefers a card the
 * user has actual progress on (so it feels personal); falls back to the daily pool.
 */
function pickCardOfTheDay(s: WidgetStoreSlice, now: number): SessionCard | null {
  const pool = dailyPoolForRole(s.role, now);
  if (!pool.length) return null;
  // Day-stable index: days-since-epoch mixed with pool length.
  const dayIndex = Math.floor(now / 86_400_000);
  const idx = ((dayIndex % pool.length) + pool.length) % pool.length;
  // Prefer a card with a real prompt; the pool is already role-filtered.
  const c = pool[idx];
  if (c && c.q) return c;
  return pool.find((p) => !!p.q) ?? null;
}

/**
 * Compute the full widget payload from the current store slice. Pure + total:
 * never throws, always returns a fully-populated `WidgetData`. Safe to call on
 * any platform (it touches only bundled content + the passed-in state).
 */
export function computeWidgetData(s: WidgetStoreSlice, now: number = Date.now()): WidgetData {
  let cardOfTheDay: WidgetData['cardOfTheDay'] = null;
  try {
    const c = pickCardOfTheDay(s, now);
    if (c) cardOfTheDay = { id: c.id, tool: c.tool, q: clip(c.q) };
  } catch {
    cardOfTheDay = null; // content lookups must never break the provider
  }
  return {
    streak: s.streak ?? 0,
    dueCount: countDue(s.progress ?? {}, now),
    cardOfTheDay,
    interviewDaysLeft: typeof s.interviewIn === 'number' ? Math.max(0, s.interviewIn) : null,
    goal: s.dailyGoal ?? 0,
    cardsToday: s.cardsToday ?? 0,
    updatedAt: now,
  };
}

/** Resolve a saved card id to a glanceable summary (used by deep-link payloads). */
export function widgetCardById(id: string): WidgetData['cardOfTheDay'] {
  const c = findCardById(id);
  return c ? { id: c.id, tool: c.tool, q: clip(c.q) } : null;
}

// ── Guarded native bridge ─────────────────────────────────────────────────────

/**
 * The native widget extension module, if present. We resolve it lazily and
 * defensively: `require` is wrapped so a missing module (Expo Go / web / a dev
 * build without the plugin) yields `null` instead of a hard crash.
 *
 * NOTE: the concrete module name depends on which approach WIDGET_SETUP.md
 * settles on. We probe both candidates so this file works regardless:
 *   - 'react-native-widget-extension'  (Live Activity JS API)
 *   - a future first-party app-groups shared-store module
 * Neither is a dependency yet, so this resolves to null today (intended).
 */
type NativeWidgetBridge = {
  // Shared App Group store (Home/lock-screen widget timeline source).
  setWidgetData?: (json: string) => void;
  reloadAllTimelines?: () => void;
  // Live Activity (ActivityKit) lifecycle.
  areActivitiesEnabled?: () => boolean;
  startActivity?: (attributes: Record<string, unknown>, content: Record<string, unknown>) => string | null;
  updateActivity?: (id: string, content: Record<string, unknown>) => void;
  endActivity?: (id: string, content?: Record<string, unknown>) => void;
};

let _bridge: NativeWidgetBridge | null | undefined;

function nativeBridge(): NativeWidgetBridge | null {
  if (_bridge !== undefined) return _bridge;
  _bridge = null;
  // Resolve lazily; any failure (module absent, web bundle, etc.) -> stay null.
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires, global-require, @typescript-eslint/no-require-imports
    const mod = require('react-native-widget-extension');
    if (mod && typeof mod === 'object') _bridge = mod as NativeWidgetBridge;
  } catch {
    _bridge = null;
  }
  return _bridge;
}

/** True only in a build where the native widget extension is actually linked. */
export function hasNativeWidget(): boolean {
  return nativeBridge() != null;
}

/**
 * Push the latest snapshot to the native widget. NO-OP (returns false) when the
 * native module isn't present — call it freely from JS without platform checks.
 *
 * Wire-up (see INTEGRATION NOTES): call after any state change that the widget
 * reflects — `store.rate()` (streak/dueCount/cardsToday change) and
 * `contentSync.initContentSync` onUpdated (card-of-the-day pool changes).
 */
export function pushWidgetUpdate(data: WidgetData): boolean {
  const bridge = nativeBridge();
  if (!bridge?.setWidgetData) return false;
  try {
    bridge.setWidgetData(JSON.stringify(data));
    bridge.reloadAllTimelines?.();
    return true;
  } catch {
    return false; // never let widget I/O break the app
  }
}

/** Convenience: compute from a store slice and push in one call. */
export function syncWidget(s: WidgetStoreSlice, now: number = Date.now()): WidgetData {
  const data = computeWidgetData(s, now);
  pushWidgetUpdate(data);
  return data;
}

// ── Live Activity (optional, iOS 16.2+) ───────────────────────────────────────

/** Whether the device currently allows Live Activities (false everywhere native is absent). */
export function liveActivitiesEnabled(): boolean {
  const bridge = nativeBridge();
  try {
    return !!bridge?.areActivitiesEnabled?.();
  } catch {
    return false;
  }
}

/**
 * Start a "daily session" Live Activity (ring + due count on the lock screen).
 * Returns the activity id, or null if unavailable. Guarded end-to-end.
 */
export function startSessionLiveActivity(data: WidgetData): string | null {
  const bridge = nativeBridge();
  if (!bridge?.startActivity || !liveActivitiesEnabled()) return null;
  try {
    return bridge.startActivity(
      { kind: 'daily-session' },
      { goal: data.goal, cardsToday: data.cardsToday, streak: data.streak, dueCount: data.dueCount }
    );
  } catch {
    return null;
  }
}

/** Update an in-flight session Live Activity. No-op when unavailable. */
export function updateSessionLiveActivity(id: string, data: WidgetData): void {
  const bridge = nativeBridge();
  if (!bridge?.updateActivity) return;
  try {
    bridge.updateActivity(id, {
      goal: data.goal,
      cardsToday: data.cardsToday,
      streak: data.streak,
      dueCount: data.dueCount,
    });
  } catch {
    /* no-op */
  }
}

/** End a session Live Activity. No-op when unavailable. */
export function endSessionLiveActivity(id: string, data?: WidgetData): void {
  const bridge = nativeBridge();
  if (!bridge?.endActivity) return;
  try {
    bridge.endActivity(id, data ? { cardsToday: data.cardsToday, streak: data.streak } : undefined);
  } catch {
    /* no-op */
  }
}
