import "server-only";
import type { IncidentScenario } from "./incidents.server";

/**
 * GENERATED by the incident-authoring agents — do not edit by hand.
 * Server-only diagnosed root-cause / fix / rubric for generated incidents,
 * keyed by problemId. Merged into incidents.server.ts.
 */
export const GENERATED_INCIDENTS: Record<string, IncidentScenario> = {};
