import "server-only";
import type { PromptOptScenario } from "./promptopt-scenarios.server";

/**
 * GENERATED by scripts/gen_promptopt.py — do not edit by hand.
 * Holds the server-only expected labels for generated promptlab items.
 */
export const GENERATED_PROMPTOPT: Record<string, PromptOptScenario> = {};
