#!/usr/bin/env node
/**
 * Developer content dump — the "see everything at once" tool.
 *
 * Reads every generated track (src/lib/generated/*.json), slices each into lesson stages exactly
 * the way the app does (chunks of LESSON_SIZE), applies the same authored/positional stage titles
 * from src/lib/lesson-titles.json, and writes a browsable CONTENT.md:
 *
 *     track  →  stage (title)  →  each question + level
 *
 * Run: `npm run dump:content`  (or `node scripts/dump-content.mjs`)
 *
 * Note: special/coding tracks (interview-craft, prompt-lab, *-oncall, *-drills, sql-coding) are
 * authored in lessons.ts / codingLessons.ts (not generated JSON) and are intentionally not included.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const GEN_DIR = join(ROOT, 'src', 'lib', 'generated');
const TITLES_PATH = join(ROOT, 'src', 'lib', 'lesson-titles.json');
const OUT_PATH = join(ROOT, 'CONTENT.md');

const LESSON_SIZE = 4; // keep in sync with content.ts LESSON_SIZE

const titlesData = JSON.parse(readFileSync(TITLES_PATH, 'utf8'));
const INDEX_LABEL = titlesData.__index ?? [];
const TITLES = titlesData.tracks ?? {};
const titleFor = (slug, idx) => TITLES[slug]?.[idx] ?? INDEX_LABEL[idx] ?? `Lesson ${idx + 1}`;

const files = readdirSync(GEN_DIR)
  .filter((f) => f.endsWith('.json'))
  .sort();

let totalCards = 0;
const lines = [];
lines.push('# ByteShards — full content dump');
lines.push('');
lines.push('_Generated by `npm run dump:content`. One section per generated track; stages mirror the in-app lesson chunks._');
lines.push('');

// Table of contents with counts.
lines.push('## Tracks');
lines.push('');
const summaries = files.map((f) => {
  const slug = f.replace(/\.json$/, '');
  const cards = JSON.parse(readFileSync(join(GEN_DIR, f), 'utf8'));
  return { slug, n: Array.isArray(cards) ? cards.length : 0 };
});
for (const s of summaries.sort((a, b) => a.n - b.n)) {
  totalCards += s.n;
  const stages = Math.ceil(s.n / LESSON_SIZE);
  lines.push(`- **${s.slug}** — ${s.n} cards · ${stages} stages`);
}
lines.push('');
lines.push(`**Total: ${totalCards} cards across ${files.length} generated tracks** (avg ${(totalCards / files.length).toFixed(1)}/track).`);
lines.push('');

// Per-track detail.
for (const f of files) {
  const slug = f.replace(/\.json$/, '');
  const cards = JSON.parse(readFileSync(join(GEN_DIR, f), 'utf8'));
  if (!Array.isArray(cards)) continue;
  const stages = Math.ceil(cards.length / LESSON_SIZE);
  lines.push('---');
  lines.push('');
  lines.push(`## ${slug} — ${cards.length} cards · ${stages} stages`);
  lines.push('');
  for (let st = 0; st < stages; st++) {
    const slice = cards.slice(st * LESSON_SIZE, st * LESSON_SIZE + LESSON_SIZE);
    lines.push(`### Stage ${st + 1} — ${titleFor(slug, st)}`);
    lines.push('');
    slice.forEach((c, k) => {
      const level = c.level ? ` _(${c.level})_` : '';
      lines.push(`${st * LESSON_SIZE + k + 1}. ${c.q}${level}`);
    });
    lines.push('');
  }
}

writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
console.log(`Wrote ${OUT_PATH}`);
console.log(`${totalCards} cards across ${files.length} generated tracks (avg ${(totalCards / files.length).toFixed(1)}/track).`);
