#!/usr/bin/env python3
"""
Codegen for interactive review items + scenarios.

Reads scripts/review_items.json (a combined list of records authored by agents)
and emits, deduped & validated:
  - lib/data/practice/review-code.generated.ts        (GENERATED_REVIEW_CODE: client-safe code under review)
  - lib/data/practice/review-scenarios.generated.server.ts (GENERATED_REVIEW_SCENARIOS: server-only issues/facts/rubric)
  - lib/data/practice/ai-review.ts                    (AIREVIEW_ITEMS, category "aireview")
  - lib/data/practice/codereview-review.ts            (CODEREVIEW_REVIEW_ITEMS, category "codereview")

Record shape (JSON):
  common: id, language, code, facts:[{q,a}], issues:[{lines:[a,b],topic,why,fix,followups:[],idealPoints:[]}], rubric:[]
  kind "item"  also has: category("codereview"|"aireview"), level, difficulty, title, company, free, prompt, hints:[]
  kind "backfill": only the common fields (the client item already exists elsewhere).

Run: python3 scripts/gen_review.py
"""
import json, re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "scripts", "review_items.json")


def existing_item_ids():
    ids = set()
    for f in ["codereview.ts", "codereview-extra.ts", "ai.ts", "prompting.ts"]:
        p = os.path.join(ROOT, "lib/data/practice", f)
        if os.path.exists(p):
            ids |= set(re.findall(r'id:\s*"([^"]+)"', open(p).read()))
    return ids


def js(x):
    return json.dumps(x, ensure_ascii=False)


def main():
    items = json.load(open(SRC))
    seen = set()
    errs = []
    for r in items:
        rid = r.get("id")
        if not rid or rid in seen:
            errs.append(f"dup/missing id: {rid}")
        seen.add(rid)
        for k in ("language", "code", "facts", "issues", "rubric"):
            if k not in r:
                errs.append(f"{rid}: missing {k}")
        lc = len((r.get("code", "")).split("\n"))
        for iss in r.get("issues", []):
            a, b = iss.get("lines", [0, 0])
            if not (1 <= a <= b <= lc):
                errs.append(f"{rid}: issue lines {iss.get('lines')} out of range 1..{lc}")
        if r.get("kind") == "item":
            for k in ("category", "level", "difficulty", "title", "company", "prompt", "hints"):
                if k not in r:
                    errs.append(f"{rid}: item missing {k}")
    # new item ids must not collide with existing items
    ex = existing_item_ids()
    for r in items:
        if r.get("kind") == "item" and r["id"] in ex:
            errs.append(f"{r['id']}: new item id collides with an existing item")
    if errs:
        print("VALIDATION FAILED:")
        for e in errs:
            print("  -", e)
        sys.exit(1)

    # ── review-code.generated.ts ──
    rc = ['import type { ConvItem } from "./types";',
          "/** GENERATED by scripts/gen_review.py — do not edit. */",
          'export const GENERATED_REVIEW_CODE: Record<string, NonNullable<ConvItem["review"]>> = {']
    for r in items:
        lc = len(r["code"].split("\n"))
        rc.append(f'  {js(r["id"])}: {{ code: {js(r["code"])}, language: {js(r["language"])}, lineCount: {lc} }},')
    rc.append("};")
    open(os.path.join(ROOT, "lib/data/practice/review-code.generated.ts"), "w").write("\n".join(rc) + "\n")

    # ── review-scenarios.generated.server.ts ──
    sc = ['import "server-only";',
          'import type { ReviewScenario } from "./review-scenarios.server";',
          "/** GENERATED by scripts/gen_review.py — do not edit. */",
          "export const GENERATED_REVIEW_SCENARIOS: Record<string, ReviewScenario> = {"]
    for r in items:
        sc.append(f'  {js(r["id"])}: {{')
        sc.append(f'    facts: {js(r["facts"])},')
        sc.append("    issues: [")
        for iss in r["issues"]:
            sc.append(f'      {{ lines: {js(iss["lines"])}, topic: {js(iss["topic"])}, why: {js(iss["why"])}, fix: {js(iss["fix"])}, followups: {js(iss["followups"])}, idealPoints: {js(iss["idealPoints"])} }},')
        sc.append("    ],")
        sc.append(f'    rubric: {js(r["rubric"])},')
        sc.append("  },")
    sc.append("};")
    open(os.path.join(ROOT, "lib/data/practice/review-scenarios.generated.server.ts"), "w").write("\n".join(sc) + "\n")

    # ── item files ──
    def emit_items(cat, var, fname, header):
        out = ['import type { ConvItem } from "./types";', header, f"export const {var}: ConvItem[] = ["]
        n = 0
        for r in items:
            if r.get("kind") != "item" or r["category"] != cat:
                continue
            n += 1
            free = "true" if r.get("free") else "false"
            out.append("  {")
            out.append(f'    id: {js(r["id"])},')
            out.append(f'    category: {js(cat)},')
            out.append("    executes: false,")
            out.append('    mode: "text",')
            out.append(f"    free: {free},")
            out.append(f'    level: {js(r["level"])},')
            out.append(f'    title: {js(r["title"])},')
            out.append(f'    company: {js(r["company"])},')
            out.append(f'    difficulty: {js(r["difficulty"])},')
            out.append(f'    prompt: {js(r["prompt"])},')
            out.append(f'    hints: {js(r["hints"])},')
            out.append('    starter: "",')
            out.append('    idealAnswer: "",')
            out.append(f'    rubric: {js(r["rubric"])},')
            out.append("  },")
        out.append("];")
        open(os.path.join(ROOT, "lib/data/practice", fname), "w").write("\n".join(out) + "\n")
        return n

    n_ai = emit_items("aireview", "AIREVIEW_ITEMS", "ai-review.ts",
                      '/** GENERATED by scripts/gen_review.py — "AI Review" interactive items. */')
    n_cr = emit_items("codereview", "CODEREVIEW_REVIEW_ITEMS", "codereview-review.ts",
                      '/** GENERATED by scripts/gen_review.py — AI-generated-code review (interactive) items. */')

    backfills = sum(1 for r in items if r.get("kind") == "backfill")
    print(f"OK — {len(items)} scenarios ({n_ai} aireview items, {n_cr} codereview items, {backfills} backfills).")


if __name__ == "__main__":
    main()
