#!/usr/bin/env python3
"""Independent validator for the content-rewrite swarm. Source of truth for the ledger.

For every track: parse the file, verify card COUNT matches the baseline (SRS identity is
positional — count/order must not change), and enforce the rewrite contract per card:
  - flip cards: `recall` present with >=2 opts, exactly one ok:true, a `why` on each option;
    `a` present; balanced `**` markers.
  - choice cards (have `opts`): exactly one ok:true, `why` on each option.
Writes scripts/rewrite-status/<track>.json {status: validated|failed, issues:[...]} and
renders REWRITE-LOG.md. Re-run anytime: python3 scripts/validate_rewrite.py
"""
import json, glob, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, 'src', 'lib', 'generated')
STATUS = os.path.join(ROOT, 'scripts', 'rewrite-status')
BASELINE = json.load(open(os.path.join(ROOT, 'scripts', 'rewrite-baseline.json')))
LOG = os.path.join(ROOT, 'REWRITE-LOG.md')

def cards_of(d):
    return d if isinstance(d, list) else (d.get('cards') or d.get('questions') or [])

def balanced_stars(s):
    return isinstance(s, str) and s.count('**') % 2 == 0

def opts_ok(opts):
    if not isinstance(opts, list) or len(opts) < 2:
        return False, 'fewer than 2 options'
    oks = sum(1 for o in opts if o.get('ok'))
    if oks != 1:
        return False, f'{oks} options marked correct (need exactly 1)'
    if any(not (o.get('why') or '').strip() for o in opts):
        return False, 'an option is missing its `why`'
    return True, ''

def validate_track(track):
    path = os.path.join(GEN, track + '.json')
    issues = []
    try:
        d = json.load(open(path))
    except Exception as e:
        return {'track': track, 'status': 'failed', 'cards': 0, 'issues': [f'parse error: {e}']}
    cards = cards_of(d)
    base = BASELINE.get(track, {}).get('cards')
    if base is not None and len(cards) != base:
        issues.append(f'card count {len(cards)} != baseline {base} (order/count must be preserved)')
    flip_ok = 0
    for i, c in enumerate(cards):
        if not isinstance(c, dict):
            issues.append(f'card {i}: not an object')
            continue
        is_choice = bool(c.get('opts'))
        if is_choice:
            ok, msg = opts_ok(c.get('opts'))
            if not ok:
                issues.append(f'card {i} opts: {msg}')
        else:
            # flip card contract
            if not (c.get('a') or '').strip():
                issues.append(f'card {i}: empty `a`')
            rec = c.get('recall')
            if not rec:
                issues.append(f'card {i}: missing `recall`')
            else:
                ok, msg = opts_ok(rec)
                if not ok:
                    issues.append(f'card {i} recall: {msg}')
                else:
                    flip_ok += 1
            if not balanced_stars(c.get('a', '')):
                issues.append(f'card {i}: unbalanced ** in `a`')
        # follow-ups balanced
        fus = c.get('followups')
        if isinstance(fus, list):
            for fu in fus:
                if isinstance(fu, dict) and not balanced_stars(fu.get('a', '')):
                    issues.append(f'card {i} followup: unbalanced **')
    status = 'validated' if not issues else 'failed'
    return {'track': track, 'status': status, 'cards': len(cards), 'recallReady': flip_ok,
            'issues': issues[:12]}

def main():
    os.makedirs(STATUS, exist_ok=True)
    results = []
    for f in sorted(glob.glob(os.path.join(GEN, '*.json'))):
        track = os.path.basename(f)[:-5]
        r = validate_track(track)
        json.dump(r, open(os.path.join(STATUS, track + '.json'), 'w'), indent=1)
        results.append(r)

    ok = [r for r in results if r['status'] == 'validated']
    bad = [r for r in results if r['status'] != 'validated']
    # render log
    L = ['# Content Rewrite Log', '',
         '> Generated by `scripts/validate_rewrite.py` (independent of agent self-reports). '
         'Re-run after each swarm wave. `failed` tracks are re-spun.', '',
         f'- **Validated:** {len(ok)}/{len(results)} tracks',
         f'- **Failed/pending:** {len(bad)}',
         f'- **Cards:** {sum(r["cards"] for r in results)}', '',
         '## Failed / pending (re-spin these)', '']
    if not bad:
        L.append('_All tracks validated._')
    else:
        L.append('| Track | Cards | First issues |')
        L.append('|---|--:|---|')
        for r in sorted(bad, key=lambda x: x['track']):
            iss = '; '.join(r['issues'][:3]).replace('|', '\\|') or 'pending (not yet rewritten)'
            L.append(f"| `{r['track']}` | {r['cards']} | {iss} |")
    L += ['', '## Validated', '', ' '.join(f"`{r['track']}`" for r in sorted(ok, key=lambda x: x['track'])) or '_none yet_', '']
    open(LOG, 'w').write('\n'.join(L) + '\n')
    print(f"validated {len(ok)}/{len(results)} | failed/pending {len(bad)}")
    if bad:
        print("re-spin:", ' '.join(r['track'] for r in bad))

if __name__ == '__main__':
    main()
