import type { TrackColorKey } from './theme';

export type CertProvider = 'databricks' | 'snowflake' | 'aws' | 'gcp' | 'azure' | 'dbt';
export type CertLevel = 'fundamentals' | 'associate' | 'professional' | 'specialist';

export interface CertDomain {
  id: string;
  name: string;
  weight: number;
  icon: string;
  objectives: string[];
  trackSlugs: string[];
  communityHighlights?: string[];
}

export interface CertDef {
  id: string;
  name: string;
  shortName: string;
  provider: CertProvider;
  level: CertLevel;
  icon: string;
  color: TrackColorKey;
  examUrl: string;
  studyGuideUrl: string;
  guideVersion: string;
  domains: CertDomain[];
  tag?: 'new' | 'updated';
}

export const CERT_PROVIDER_LABEL: Record<CertProvider, string> = {
  databricks: 'Databricks',
  snowflake: 'Snowflake',
  aws: 'AWS',
  gcp: 'Google Cloud',
  azure: 'Azure',
  dbt: 'dbt',
};

export const CERT_PROVIDER_ORDER: CertProvider[] = ['databricks', 'snowflake', 'aws', 'gcp', 'azure', 'dbt'];

export const CERTS: CertDef[] = [
  // ─────────────────────────────────────────────────────────────
  // Databricks Certified Data Engineer Associate
  // ─────────────────────────────────────────────────────────────
  {
    id: 'databricks-de-associate',
    name: 'Databricks Certified Data Engineer Associate',
    shortName: 'DE Associate',
    provider: 'databricks',
    level: 'associate',
    icon: '🏗️',
    color: 'spark',
    examUrl: 'https://www.databricks.com/learn/certification/data-engineer-associate',
    studyGuideUrl:
      'https://www.databricks.com/sites/default/files/2026-05/databricks-certified-data-engineer-associate-exam-guide-may-2026-000.pdf',
    guideVersion: 'May 2026',
    domains: [
      {
        id: 'databricks-intelligence-platform',
        name: 'Databricks Intelligence Platform',
        weight: 10,
        icon: '🏗️',
        objectives: [
          'Describe the architecture and components of the Databricks Data Intelligence Platform',
          'Identify appropriate compute types for specific use cases (all-purpose clusters vs. job clusters vs. SQL warehouses vs. serverless compute)',
          'Understand workspace components: notebooks, clusters, DBFS, Repos, Workflows, and secrets',
          'Describe the Lakehouse architecture and how Delta Lake underpins it',
          'Explain the benefits of the Databricks Lakehouse over traditional data warehouses and data lakes',
          'Understand Photon engine and its role in query acceleration',
          'Navigate workspace UI and use key features (notebooks, job runs, cluster management)',
          'Identify when to use Delta Lake vs. other storage formats',
        ],
        trackSlugs: ['databricks', 'spark'],
        communityHighlights: [
          "Smallest domain at 10% — don't over-invest, but don't skip it entirely",
          'Cluster type selection (all-purpose vs. job vs. SQL warehouse) appears frequently',
          'Serverless compute advantages over classic compute are tested',
          'Lakehouse architecture definition and its differentiation from data lakes/warehouses is foundational',
          'Unity Catalog three-level namespace (catalog.schema.table) is referenced across all domains',
        ],
      },
      {
        id: 'development-and-ingestion',
        name: 'Development and Ingestion',
        weight: 30,
        icon: '📥',
        objectives: [
          'Implement Auto Loader for incremental file ingestion from cloud object storage',
          'Classify valid Auto Loader source types and understand schema inference and schema evolution behavior',
          'Differentiate between Auto Loader and COPY INTO for batch vs. streaming ingestion use cases',
          'Use Databricks Connect for remote development workflows',
          'Ingest semi-structured and unstructured data (JSON, nested types) using Lakeflow Connect and managed connectors',
          'Prioritize between ingestion methods (Auto Loader, Lakeflow Connect, COPY INTO, partner connectors) based on volume, frequency, and governance requirements',
          'Understand notebook magic commands, widgets, and collaboration features',
          'Read and write data across file formats (CSV, JSON, Parquet, Avro, ORC) and Delta',
          'Understand Delta Lake ACID properties, time travel, schema evolution, and schema enforcement',
          'Create and manage views: temporary views, global temporary views, and permanent views',
          'Use UDFs (user-defined functions) in SQL and Python',
          'Apply structured streaming basics: triggers, watermarking, checkpointing, exactly-once semantics',
          'Understand Lakeflow Connect standard and managed connectors',
        ],
        trackSlugs: ['databricks', 'spark', 'pyspark', 'sql', 'python'],
        communityHighlights: [
          'Auto Loader is the single most heavily tested topic in this domain — expect multiple scenario questions on sources, schema evolution, and syntax',
          'Know the difference between Auto Loader (streaming incremental) and COPY INTO (batch idempotent)',
          'Schema inference and evolution with cloudFiles format is a common question pattern',
          'Always specify checkpoint location for streaming workloads — frequently tested gotcha',
          'Lakeflow Connect (formerly ingestion connectors) is new in 2025 exam — know when to choose it over Auto Loader',
        ],
      },
      {
        id: 'data-processing-transformations',
        name: 'Data Processing & Transformations',
        weight: 31,
        icon: '⚙️',
        objectives: [
          'Describe the Medallion Architecture (Bronze/Silver/Gold layers) and the purpose of each layer',
          'Build Lakeflow Spark Declarative Pipelines (formerly Delta Live Tables) end-to-end',
          'Define data quality expectations in Lakeflow pipelines using @dlt.expect, @dlt.expect_or_drop, @dlt.expect_or_fail',
          'Understand lazy evaluation in Apache Spark and the difference between transformations and actions',
          'Write complex Spark SQL queries: SELECT, WHERE, GROUP BY, window functions, JOINs',
          'Execute DDL/DML operations: CREATE TABLE, ALTER TABLE, INSERT, INSERT OVERWRITE, UPDATE, DELETE, MERGE INTO',
          'Implement MERGE INTO for upsert patterns (SCD Type 1 and Type 2)',
          'Perform Delta Lake optimizations: OPTIMIZE (file compaction), ZORDER (data skipping), VACUUM (file cleanup), Liquid Clustering',
          'Use Delta Lake time travel for auditing and rollback',
          'Apply incremental processing patterns with structured streaming on Delta tables',
          'Implement deduplication strategies in streaming and batch workloads',
          'Build multi-hop pipelines (Bronze→Silver→Gold) with incremental updates',
          'Use PySpark DataFrame API: select, filter, withColumn, groupBy, agg, join, union',
          'Understand Change Data Feed (CDF) on Delta tables',
          'Apply SQL UDFs and Python UDFs within transformations',
        ],
        trackSlugs: ['databricks', 'spark', 'pyspark', 'sql', 'python'],
        communityHighlights: [
          'Largest domain at 31% — most candidates pass or fail here; deep hands-on practice is essential',
          'Lakeflow Spark Declarative Pipelines (renamed from Delta Live Tables) is the most technically demanding topic',
          'MERGE INTO syntax and upsert logic is heavily tested with code-snippet questions',
          'Delta Lake optimizations (OPTIMIZE, ZORDER, VACUUM, Liquid Clustering) appear frequently — know when to use each',
          'VACUUM default retention of 7 days should never be dropped below in production — common trick question',
        ],
      },
      {
        id: 'productionizing-data-pipelines',
        name: 'Productionizing Data Pipelines',
        weight: 18,
        icon: '🚀',
        objectives: [
          'Create and manage Databricks Workflows (Jobs) with multi-task dependencies',
          'Configure job clusters vs. all-purpose clusters for production workload cost optimization',
          'Use Databricks Asset Bundles (DABs) for CI/CD and infrastructure-as-code deployments',
          'Implement idempotent pipeline patterns to ensure safe reruns',
          'Configure task failure handling, retries, and alerting in Jobs',
          'Monitor pipeline performance using Spark UI (DAG, stages, tasks, shuffle metrics)',
          'Understand serverless compute advantages for Workflows and SQL',
          'Deploy workloads with Lakeflow Jobs including task types (notebook, Python script, SQL, Delta Live Tables pipeline)',
          'Apply DevOps essentials: version control with Repos, testing strategies, deployment pipelines',
          'Understand performance optimization: caching, broadcast joins, partition strategies',
          'Configure monitoring and alerting for production data pipelines',
          'Use run-time parameters and widgets for parameterized pipelines',
          'Understand data interoperability with Delta Sharing and Lakehouse Federation',
        ],
        trackSlugs: ['databricks', 'spark', 'sql', 'python'],
        communityHighlights: [
          'Databricks Asset Bundles (DABs) are newer functionality — many practitioners lack hands-on experience, creating a common knowledge gap',
          'Spark UI analysis for identifying bottlenecks (wide vs. narrow transformations, shuffle, spill) is tested with scenario questions',
          'Job cluster vs. all-purpose cluster cost trade-offs appear regularly',
          'Idempotent pipeline design and safe rerun patterns are tested conceptually',
          'Delta Sharing and Lakehouse Federation are new to this domain in the July 2025 update',
        ],
      },
      {
        id: 'data-governance-quality',
        name: 'Data Governance & Quality',
        weight: 11,
        icon: '🔐',
        objectives: [
          'Navigate the Unity Catalog three-level namespace (catalog.schema.table)',
          'Grant and revoke permissions at catalog, schema, and table levels using GRANT/REVOKE syntax',
          'Understand key Unity Catalog roles: metastore admin, catalog owner, schema owner, table owner',
          'Differentiate between managed tables and external tables and their lifecycle implications',
          'Configure row-level security and column-level security (column masking)',
          'Use data lineage tracking in Unity Catalog and understand what is captured automatically',
          'Configure and query audit logs for compliance and security monitoring',
          'Understand Delta Sharing: use cases, configuration, and limitations',
          'Configure Lakehouse Federation for querying external databases without data movement',
          'Apply table constraints (NOT NULL, CHECK, primary key, foreign key) in Delta Lake',
          'Implement data quality checks and expectations in pipelines',
          'Understand external locations and storage credentials in Unity Catalog',
        ],
        trackSlugs: ['databricks', 'data-governance', 'sql'],
        communityHighlights: [
          'Unity Catalog appears throughout the entire exam beyond this domain — mastery of the three-level namespace is essential for all domains',
          'Security and governance questions are easy to miss without hands-on experience — practice GRANT/REVOKE syntax',
          'Data lineage is captured automatically by Unity Catalog without manual setup — a common misconception tested',
          'Delta Sharing and Lakehouse Federation moved to higher emphasis in July 2025 update',
          'Managed vs. external table lifecycle differences (drop behavior, data deletion) is a frequent scenario question',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // Databricks Certified Data Engineer Professional
  // ─────────────────────────────────────────────────────────────
  {
    id: 'databricks-de-professional',
    name: 'Databricks Certified Data Engineer Professional',
    shortName: 'DE Pro',
    provider: 'databricks',
    level: 'professional',
    icon: '🏗️',
    color: 'spark',
    examUrl: 'https://www.databricks.com/learn/certification/data-engineer-professional',
    studyGuideUrl:
      'https://files.training.databricks.com/static/docs/databricks-certified-data-engineer-professional-exam-guide.pdf',
    guideVersion: '2026',
    domains: [
      {
        id: 'code-for-data-processing',
        name: 'Developing Code for Data Processing using Python and SQL',
        weight: 22,
        icon: '🐍',
        objectives: [
          'Design scalable Python project structures optimized for Databricks Asset Bundles (DABs)',
          'Manage external library installations and third-party dependency management',
          'Develop Pandas UDFs and Python UDFs for custom transformations',
          'Build production-ready batch and streaming data pipelines using Lakeflow Spark Declarative Pipelines',
          'Implement Auto Loader for incremental data ingestion from cloud storage',
          'Automate ETL workflows using Lakeflow Jobs (Databricks Workflows)',
          'Write unit tests and integration tests for data pipeline code',
          'Apply APPLY CHANGES API for CDC with Lakeflow Declarative Pipelines',
          'Structure modular PySpark code for maintainability and testability',
        ],
        trackSlugs: ['databricks', 'pyspark', 'python', 'sql', 'kafka'],
        communityHighlights: [
          'Largest domain at 22% — expect 13+ questions on PySpark/Spark SQL and DABs project structure',
          'Asset Bundles (DABs) are a heavily tested new topic added in the November 2025 exam update',
          'Lakeflow Declarative Pipelines (formerly DLT) new syntax and APPLY CHANGES API are critical',
          'Auto Loader configuration and incremental file detection patterns appear frequently',
          'UDFs (both Python and Pandas) are tested in the context of performance trade-offs',
        ],
      },
      {
        id: 'data-ingestion-acquisition',
        name: 'Data Ingestion & Acquisition',
        weight: 7,
        icon: '📥',
        objectives: [
          'Design pipelines that handle diverse data formats: Delta Lake, Parquet, ORC, AVRO, JSON, CSV, XML, text, binary',
          'Ingest data from message buses (e.g., Kafka, Event Hubs) and cloud object storage',
          'Create append-only ingestion pipelines for batch and streaming data',
          'Configure Auto Loader with schema inference and schema hints',
          'Implement idempotent ingestion patterns using checkpointing',
        ],
        trackSlugs: ['databricks', 'spark', 'pyspark', 'kafka', 'sql'],
        communityHighlights: [
          'Auto Loader is covered here AND in domain 1 — expect overlap questions on file notification vs. directory listing modes',
          'Kafka source configuration with Structured Streaming tested at a practical level',
          'Format-specific read options (inferSchema, mergeSchema, rescuedDataColumn) appear in practice exams',
          'Append-only vs. upsert pipeline design trade-offs are commonly tested',
        ],
      },
      {
        id: 'data-transformation-quality',
        name: 'Data Transformation, Cleansing, and Quality',
        weight: 10,
        icon: '🔧',
        objectives: [
          'Write efficient Spark SQL and PySpark code for advanced transformations',
          'Implement window functions (RANK, DENSE_RANK, ROW_NUMBER, LAG, LEAD, running aggregations)',
          'Perform complex joins including broadcast joins, skew joins, and anti-joins',
          'Apply advanced aggregations: pivot, rollup, cube',
          'Develop quarantine (dead-letter) processes for poor-quality data',
          'Implement data quality checks and constraints using Delta Lake table constraints',
          'Handle schema evolution and mergeSchema scenarios',
          'Use EXPECTATIONS in Lakeflow Declarative Pipelines for data quality enforcement',
        ],
        trackSlugs: ['databricks', 'spark', 'pyspark', 'sql', 'dbt'],
        communityHighlights: [
          'Window functions are tested in depth — expect multi-step SQL/PySpark problems',
          'EXPECTATIONS in DLT/Lakeflow pipelines (warn, drop, fail modes) are a frequently tested new topic',
          'Quarantine pattern (routing bad records to separate table) appears in scenario questions',
          'Complex join optimization — broadcast hints and skew handling — tested at professional level',
        ],
      },
      {
        id: 'data-sharing-federation',
        name: 'Data Sharing and Federation',
        weight: 5,
        icon: '🔗',
        objectives: [
          'Configure Delta Sharing between Databricks deployments using open sharing protocols',
          'Share live Delta Lake data to non-Databricks platforms using Delta Sharing',
          'Implement Lakehouse Federation with proper Unity Catalog governance',
          'Configure foreign catalogs and foreign tables for federated queries',
          'Manage Delta Share providers, recipients, and shares',
        ],
        trackSlugs: ['databricks', 'data-governance', 'sql'],
        communityHighlights: [
          'Delta Sharing open protocol vs. Databricks-to-Databricks sharing distinction is commonly tested',
          'Lakehouse Federation foreign catalog setup steps appear in scenario questions',
          'Recipient token management and IP allow-listing in Delta Sharing tested',
          'Understanding what data types CAN be shared (Delta tables, not streaming) is important',
        ],
      },
      {
        id: 'monitoring-alerting',
        name: 'Monitoring and Alerting',
        weight: 10,
        icon: '📊',
        objectives: [
          'Use system tables for observability over resource utilization, cost, auditing, and workload monitoring',
          'Leverage Query Profiler UI and Spark UI for diagnosing query performance issues',
          'Utilize REST APIs and Databricks CLI for job and pipeline monitoring',
          'Set up SQL Alerts for data quality threshold violations',
          'Configure Lakeflow Job email and webhook notifications for failure/success',
          'Monitor streaming pipelines using event logs and metrics',
          'Design resilient long-running pipeline architectures with retry and error handling',
        ],
        trackSlugs: ['databricks', 'spark', 'sql', 'data-reliability'],
        communityHighlights: [
          'System tables (system.billing, system.access, system.compute, system.lakeflow) are a new heavily tested topic in 2025 exam update',
          'Spark UI interpretation — identifying shuffle spill, skew, and stage bottlenecks — appears frequently',
          'SQL Alerts configuration and threshold logic tested in practical scenarios',
          'Job cluster vs. all-purpose cluster cost monitoring differences are tested',
        ],
      },
      {
        id: 'cost-performance-optimization',
        name: 'Cost & Performance Optimization',
        weight: 13,
        icon: '⚡',
        objectives: [
          'Understand Unity Catalog managed tables and their storage optimization implications',
          'Apply Delta Lake optimization techniques: deletion vectors, Liquid Clustering, OPTIMIZE, ZORDER, VACUUM',
          'Identify when to use Liquid Clustering vs. partitioning vs. Z-Ordering',
          'Apply Change Data Feed (CDF) to reduce full-table scans in streaming pipelines',
          'Use Query Profiles to identify and remediate bottlenecks (shuffle, spill, skew)',
          'Configure Photon engine and serverless compute for cost optimization',
          'Tune Spark configurations: parallelism, shuffle partitions, broadcast thresholds',
          'Implement caching strategies for repeated query patterns',
          'Optimize file sizes using OPTIMIZE and auto-optimize settings',
        ],
        trackSlugs: ['databricks', 'spark', 'pyspark', 'sql'],
        communityHighlights: [
          'Second largest domain at 13% — Liquid Clustering is the biggest new topic replacing Z-Order/partition decisions',
          'ZORDER vs. partitioning vs. Liquid Clustering trade-off questions are heavily tested in 2025/2026 version',
          'Deletion vectors (soft deletes) vs. REWRITE mode for MERGE operations tested',
          'Change Data Feed enabling and reading for downstream streaming consumers is a common question type',
          'Photon vs. standard Spark — when to use each — appears in cost optimization scenarios',
        ],
      },
      {
        id: 'data-security-compliance',
        name: 'Ensuring Data Security and Compliance',
        weight: 10,
        icon: '🔒',
        objectives: [
          'Implement ACLs (Access Control Lists) for data objects, jobs, and clusters',
          'Configure row filters and column masks in Unity Catalog for fine-grained access',
          'Apply anonymization and pseudonymization methods: hashing, tokenization, masking',
          'Detect and mask PII data compliantly using Unity Catalog policies',
          'Implement data purging and retention solutions (GDPR right-to-be-forgotten)',
          'Manage secrets using Databricks Secret Scopes (Azure Key Vault, Databricks-backed)',
          'Configure network security: IP access lists, private endpoints, VNet injection',
          'Audit data access using system tables and Unity Catalog audit logs',
        ],
        trackSlugs: ['databricks', 'data-governance', 'sql'],
        communityHighlights: [
          'Row filters and column masks are new Unity Catalog features heavily tested in 2025 exam update',
          'PII detection and compliant masking patterns appear in multi-step scenario questions',
          'GDPR right-to-erasure implementation using Delta Lake GDPR DELETE is a common scenario',
          'Secret scope creation and secret ACLs tested with practical code examples',
          'Unity Catalog privilege model (USE CATALOG, USE SCHEMA, SELECT, MODIFY) hierarchy is critical',
        ],
      },
      {
        id: 'data-governance',
        name: 'Data Governance',
        weight: 7,
        icon: '🏛️',
        objectives: [
          'Create discoverable metadata: table descriptions, column comments, and tags in Unity Catalog',
          'Demonstrate Unity Catalog permission inheritance model (catalog → schema → table)',
          'Configure data lineage tracking and use lineage UI in Unity Catalog',
          'Implement data classification using Unity Catalog tags',
          'Manage Unity Catalog metastore, catalogs, schemas, and external locations',
          'Configure storage credentials and external locations for cloud storage access',
        ],
        trackSlugs: ['databricks', 'data-governance', 'sql'],
        communityHighlights: [
          'Unity Catalog permission inheritance — securable objects hierarchy — is the most tested governance topic',
          'Data lineage (table-level and column-level) capabilities and limitations tested',
          'Difference between Hive metastore and Unity Catalog governance models is a common question',
          'Tags vs. comments vs. descriptions distinctions tested in practical scenarios',
        ],
      },
      {
        id: 'debugging-deploying',
        name: 'Debugging and Deploying',
        weight: 10,
        icon: '🚀',
        objectives: [
          'Identify diagnostic information via Spark UI, cluster event logs, system tables, and query profiles',
          'Analyze Python, Scala, and SQL stack traces to identify root cause of pipeline failures',
          'Remediate failed Lakeflow Job runs using repair and re-run capabilities',
          'Build and deploy Databricks resources using Databricks Asset Bundles (DABs)',
          'Configure Git-based CI/CD workflows with Databricks Repos and DABs',
          'Use Databricks CLI for deployment automation and environment promotion',
          'Implement blue-green and canary deployment patterns for pipelines',
          'Manage environment-specific configurations in DABs (dev/staging/prod targets)',
        ],
        trackSlugs: ['databricks', 'python', 'sql'],
        communityHighlights: [
          'Asset Bundles deployment workflow (bundle.yml structure, targets, resources) heavily tested in 2025 update',
          'Git CI/CD integration with DABs — triggering deployments, environment promotion — is new exam content',
          'Repair run vs. full re-run for failed Job tasks tested with scenario questions',
          'Reading Spark UI event timeline to diagnose GC overhead, spill, and skew appears frequently',
        ],
      },
      {
        id: 'data-modelling',
        name: 'Data Modelling',
        weight: 6,
        icon: '🗂️',
        objectives: [
          'Design scalable Delta Lake data models for the Lakehouse (Medallion Architecture: Bronze/Silver/Gold)',
          'Optimize query performance using Liquid Clustering for data layout decisions',
          'Identify the benefits of Liquid Clustering over static partitioning and Z-Ordering',
          'Implement Slowly Changing Dimensions (SCD Type 1 and Type 2) using Delta Lake MERGE',
          'Design fact and dimension table schemas for analytics workloads',
          'Apply schema evolution strategies in a multi-hop pipeline',
        ],
        trackSlugs: ['databricks', 'sql', 'modeling'],
        communityHighlights: [
          'Medallion Architecture design decisions (what goes in Bronze vs. Silver vs. Gold) tested in scenario questions',
          'SCD Type 2 implementation with MERGE INTO is a classic exam question type',
          'Liquid Clustering key selection strategy — cardinality and query filter patterns — tested in 2025 update',
          'Fact vs. dimension table design for Lakehouse analytics appears in practical scenarios',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // Databricks Certified Generative AI Engineer Associate
  // ─────────────────────────────────────────────────────────────
  {
    id: 'databricks-genai-associate',
    name: 'Databricks Certified Generative AI Engineer Associate',
    shortName: 'GenAI Associate',
    provider: 'databricks',
    level: 'associate',
    icon: '🤖',
    color: 'rag',
    examUrl: 'https://www.databricks.com/learn/certification/genai-engineer-associate',
    studyGuideUrl:
      'https://www.scribd.com/document/820429291/Databricks-Exam-Guide-Generative-AI-Engineer-Associate-Exam-Guide',
    guideVersion: '2026',
    tag: 'new',
    domains: [
      {
        id: 'design-applications',
        name: 'Design Applications',
        weight: 14,
        icon: '🏗️',
        objectives: [
          'Design prompts that elicit specifically formatted responses (structured output prompting)',
          'Select appropriate model tasks for given business requirements',
          'Translate business use case goals into descriptions of desired AI pipeline inputs and outputs',
          'Select chain components appropriate for a given task',
          'Define and order tools that gather knowledge for multi-stage reasoning pipelines',
          'Select appropriate Agent Bricks for use cases (Knowledge Assistant, Multi-Agent Supervisor, Information Extraction)',
          'Decompose complex LLM-enabled application requirements into manageable sub-tasks',
          'Identify when to use zero-shot, few-shot, prompt chaining, and meta-prompt strategies',
        ],
        trackSlugs: ['llms', 'prompt', 'agents', 'databricks'],
        communityHighlights: [
          'Foundation knowledge section — understand prompt design patterns (zero-shot, few-shot, chain-of-thought) before moving to heavier sections',
          'Agent Bricks selection (Knowledge Assistant vs Multi-Agent Supervisor vs Information Extraction) added in March 2026 update — expect 1-2 questions',
          'Questions test your ability to map a business scenario to the correct pipeline shape, not just recite definitions',
          'Multi-stage reasoning tool ordering is a common scenario-based question type',
          'Relatively lighter section at 14% — don\'t over-invest study time here compared to Application Development',
        ],
      },
      {
        id: 'data-preparation',
        name: 'Data Preparation',
        weight: 14,
        icon: '🗂️',
        objectives: [
          'Select chunking strategies appropriate for different document structures (fixed-size, semantic, sentence, paragraph)',
          'Apply advanced chunking approaches including context-aware chunking and windowed summarization',
          'Filter content to improve RAG retrieval quality',
          'Extract data from various document formats using Python-based extraction tools',
          'Integrate data with Delta Lake and Unity Catalog for governed RAG pipelines',
          'Identify source documents from which to retrieve knowledge',
          'Evaluate retrieval performance using appropriate tools and metrics',
          'Apply re-ranking techniques to improve retrieval precision',
          'Select embedding models based on context length and domain requirements',
          'Understand how chunking strategy choices impact downstream model performance',
        ],
        trackSlugs: ['rag', 'databricks', 'python', 'data-governance'],
        communityHighlights: [
          'RAG data pipeline knowledge bleeds across multiple domains — mastering chunking here pays dividends in Application Development too',
          "Chunking trade-offs (fixed-size vs semantic vs sentence) are frequently tested as scenario questions: 'given this document type, which strategy?'",
          'Re-ranking with cross-encoders vs bi-encoders is a recurring topic in community study groups',
          'Content filtering for safety and quality (removing irrelevant or harmful source content) is tested alongside governance',
          'Embedding model selection criteria (context window length, multilingual support) appears in both this domain and Application Development',
        ],
      },
      {
        id: 'application-development',
        name: 'Application Development',
        weight: 30,
        icon: '⚙️',
        objectives: [
          'Select appropriate LangChain or Mosaic AI Agent Framework tools for generative AI applications',
          'Assess LLM responses for quality and safety issues',
          'Refine chunking strategies based on evaluation feedback loops',
          'Augment prompts with user context and conversation history',
          'Adjust LLM response behavior through advanced prompting techniques',
          'Implement guardrails for input and output safety (PII redaction, toxicity filtering)',
          'Select LLMs based on application attributes (latency, cost, quality, context window, modality)',
          'Select embedding models based on context length and performance requirements',
          'Use model hub or marketplace to discover and select foundation models',
          'Select models via MLflow experiment tracking metrics',
          'Integrate MLflow with Mosaic AI Agent Framework for lifecycle management',
          'Distinguish between evaluation phase and monitoring phase responsibilities',
          'Build multi-agent systems using Genie Spaces and multi-agent collaboration patterns',
          'Implement agentic AI with LangChain and LangGraph (ReAct, tool use, planning, multi-agent patterns)',
          'Apply context injection and few-shot learning in production chains',
          'Code end-to-end RAG solutions: parsing, chunking, retrieval, and response generation',
        ],
        trackSlugs: ['rag', 'agents', 'llms', 'databricks', 'python', 'prompt', 'agentic-ai', 'evals'],
        communityHighlights: [
          'Largest domain at 30% — build a complete agent end-to-end at least once before the exam; hands-on beats memorization',
          'LangChain and LangGraph agentic patterns (ReAct, tool use, planning) appear heavily — understand when to choose each reasoning strategy',
          'Guardrail implementation (input/output filtering, PII redaction) is tested more practically than conceptually — know the Databricks-native approaches',
          'LLM selection questions are scenario-based: given latency/cost/quality constraints, which model/configuration is optimal',
          'MLflow integration with Agent Framework is central — understand how to log, track, and compare experiments for LLM applications',
        ],
      },
      {
        id: 'assembling-deploying-apps',
        name: 'Assembling and Deploying Applications',
        weight: 22,
        icon: '🚀',
        objectives: [
          'Code PyFunc chains with pre- and post-processing logic',
          'Control access to resources from Model Serving endpoints',
          'Code simple LangChain chains according to given requirements',
          'Identify elements needed for RAG applications (model flavor, embedding model, retriever, dependencies, input examples, model signature)',
          'Register models to Unity Catalog using MLflow',
          'Sequence deployment steps for basic RAG applications',
          'Create and query Databricks Vector Search indexes',
          'Serve LLM applications leveraging Foundation Model APIs',
          'Identify resources needed to serve features for RAG applications',
          'Explain key concepts and components of Mosaic AI Vector Search',
          'Identify batch inference workloads and apply ai_query() appropriately',
          'Configure Vector Search for latency and cost optimization (standard vs storage-optimized)',
          'Implement persistent agent memory using appropriate datastores',
          'Apply CI/CD best practices for agent deployment pipelines',
          'Integrate MCP servers (managed, external, custom) into agent workflows',
          'Use MLflow Prompt Registry for prompt version control and lifecycle management',
          'Build agent user interfaces with Databricks Apps, Slack, and Teams integrations',
        ],
        trackSlugs: ['databricks', 'mlsys', 'rag', 'agents', 'python', 'agentic-ai'],
        communityHighlights: [
          'Six new objectives added in March 2026: MCP servers, Prompt Registry, CI/CD for agents, persistent memory, storage-optimized Vector Search, Databricks Apps — all likely to appear on current exam',
          'Vector Search configuration trade-offs (standard vs storage-optimized, hybrid BM25+vector) are a common question type',
          'PyFunc model packaging with pre/post-processing is a hands-on skill tested practically — know the MLflow pyfunc API',
          'ai_query() for batch inference is a Databricks-specific function that appears regularly in scenario questions',
          'Unity Catalog model registration steps (log → register → alias → promote) form a frequent multi-step scenario question',
        ],
      },
      {
        id: 'governance',
        name: 'Governance',
        weight: 8,
        icon: '🔒',
        objectives: [
          'Apply masking techniques as guardrails to meet performance and compliance objectives',
          'Protect LLM applications against malicious inputs (prompt injection, jailbreaking)',
          'Manage legal and licensing requirements for models and training data',
          'Mitigate problematic text in generative AI data sources',
          'Implement multi-tenant data isolation using Unity Catalog',
          'Apply ethical AI oversight principles in GenAI system design',
          'Use Databricks Mosaic AI Gateway for policy enforcement and access control',
        ],
        trackSlugs: ['data-governance', 'databricks', 'llms'],
        communityHighlights: [
          'Lightest domain at 8% — allocate ~3-4 days study time, not a full week',
          'AI Gateway is the primary governance enforcement mechanism on Databricks — know its rate limiting, usage tracking, and policy features',
          'Prompt injection and jailbreak mitigation techniques overlap with Application Development guardrails section',
          "Legal/licensing (open-source model licenses: Apache 2.0 vs GPL vs proprietary) appears as a scenario: 'can you use this model commercially?'",
          'Unity Catalog row-level and column-level security for RAG data sources is tested alongside the main governance theme',
        ],
      },
      {
        id: 'evaluation-and-monitoring',
        name: 'Evaluation and Monitoring',
        weight: 12,
        icon: '📊',
        objectives: [
          'Select LLMs based on evaluation metrics from MLflow experiments',
          'Identify and apply key metrics for LLM monitoring (perplexity, toxicity, latency, throughput)',
          'Evaluate agents using MLflow Scoring and MLflow Tracing',
          'Use inference logging to assess production performance',
          'Control LLM cost using AI Gateway usage tables and rate limiting',
          'Use inference tables and Agent Monitoring to track serving endpoints',
          'Identify appropriate evaluation judges and ground truth data sources',
          'Use AI Gateway to track Inference Tables and Usage Tables',
          'Build custom Scorers for domain-specific evaluation',
          'Incorporate SME (subject matter expert) feedback into evaluation pipelines',
          'Apply RAG evaluation metrics: context precision, context recall, answer relevance, faithfulness',
          'Distinguish between component-level and end-to-end evaluation approaches',
        ],
        trackSlugs: ['evals', 'databricks', 'mlsys', 'llms', 'rag'],
        communityHighlights: [
          'MLflow 3 (Tracing, Scoring, Prompt Registry) replaced the older Agent Evaluation framework — study the new API, not the legacy one',
          "RAG-specific metrics (context precision, faithfulness, answer relevance, context recall) are tested as 'which metric measures X' scenario questions",
          'AI Gateway Inference Tables and Usage Tables are both tested: know the difference between what each tracks',
          'Custom Scorers (added March 2026) and SME feedback incorporation are new objectives likely to appear as 1-2 questions',
          'End-to-end vs component-level evaluation distinction is a conceptual question that appears in multiple community practice tests',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // Databricks Certified Context Engineer Associate
  // ─────────────────────────────────────────────────────────────
  {
    id: 'databricks-context-engineer',
    name: 'Databricks Certified Context Engineer Associate',
    shortName: 'Context Engineer',
    provider: 'databricks',
    level: 'associate',
    icon: '🧠',
    color: 'eval',
    examUrl: 'https://www.databricks.com/learn/certification/context-engineer-associate',
    studyGuideUrl:
      'https://www.databricks.com/sites/default/files/2026-05/databricks-certified-context-engineer-associate-exam-guide-beta.pdf',
    guideVersion: 'BETA (June 2026)',
    tag: 'new',
    domains: [
      {
        id: 'foundations-context-engineering',
        name: 'Foundations of Context Engineering',
        weight: 16,
        icon: '🧱',
        objectives: [
          'Given a described agent failure, identify the context management technique that would most directly address it.',
          'Given a Databricks agent design, identify which proactive context management strategies (e.g., minimal toolsets, just-in-time retrieval, tool result scoping) would reduce context window pressure before compaction becomes necessary.',
          'Diagnose context failure modes: context poisoning, context distraction, context confusion, and context clash, given an agent trace.',
          'Select the right tool in the Databricks product stack (Unity Catalog, Lakebase, MCP, MLflow 3) for a given scenario.',
          'Given a described agent configuration, identify which context elements are consuming disproportionate attention budget and select the change most likely to improve model focus.',
          'Given a Databricks agent task and its performance requirements, select the appropriate reasoning mode (standard, extended thinking, or reduced thinking) and justify the selection based on token budget constraints and context window impact.',
          'Given a Databricks agent operating over an extended interaction, identify the point at which context length is causing measurable degradation in retrieval accuracy or reasoning quality, and select the intervention that restores performance.',
        ],
        trackSlugs: ['databricks', 'agents', 'llms', 'agentic-ai'],
        communityHighlights: [
          'This is a beta exam first offered at DAIS 2026 (June 16-18); no community pass reports exist yet as results are released 6 weeks after Summit.',
          'Context failure modes (poisoning, distraction, confusion, clash) appear prominently in objectives — know how to diagnose from an agent trace.',
          'Requires deep familiarity with the Databricks product stack: Unity Catalog, Lakebase, MCP, MLflow 3.',
          'Reasoning mode selection (standard vs extended vs reduced thinking) and token budget tradeoffs are explicitly tested.',
          'Proactive context management strategies (minimal toolsets, JIT retrieval) are emphasized before reactive compaction.',
        ],
      },
      {
        id: 'system-prompt-instruction-design',
        name: 'System Prompt and Instruction Design',
        weight: 9,
        icon: '✍️',
        objectives: [
          'Given a business domain, select and validate the instructions, sample questions, and trusted SoL assets that together produce a production-ready Genie space.',
          'Given a set of candidate few-shot examples for a Databricks agent, evaluate each against canonical coverage criteria and select the minimal set that improves agent performance without inflating token cost.',
          'Given a miscalibrated Databricks agent system prompt and its observed failure pattern, select the targeted revision strategy that resolves the failure with the least increase in token cost and maintenance burden.',
          'Given experiment tracking results comparing two system prompt configurations on a Databricks agent, determine whether the higher-token configuration is justified and identify the specific prompt element driving the cost-performance tradeoff.',
        ],
        trackSlugs: ['databricks', 'prompt', 'agents', 'llms'],
        communityHighlights: [
          'Lowest-weight domain at 9% — focuses on Genie space configuration and few-shot example curation.',
          'Token cost vs. performance tradeoffs in prompt design are a recurring theme across all domains.',
          'Genie space setup requires knowledge of SoL (Sources of Logic) assets, trusted tables, and sample questions.',
          'MLflow experiment tracking is used to compare prompt configurations — know how to read experiment results.',
          'Prompt revision should minimize maintenance burden, not just immediate token cost.',
        ],
      },
      {
        id: 'knowledge-retrieval-genie-configuration',
        name: 'Knowledge Retrieval and Genie Configuration',
        weight: 20,
        icon: '🔍',
        objectives: [
          'Given an underperforming Databricks agent and its associated Unity Catalog metadata, identify which missing or poorly specified metadata elements are causing the accuracy gap and select the configuration change that will have the highest impact on agent performance.',
          'Select which Unity Catalog objects (managed tables, views, parameterized queries, SoL functions) to curate into a Genie space for a given business domain.',
          'Given a Databricks agent with documented retrieval quality problems, diagnose which Vector Search configuration is the root cause and select the remediation that most directly improves the signal quality of retrieved context.',
          'Design a RAG pipeline that retrieves chunks from a Unity Catalog-governed document corpus and injects them into agent context.',
          'Select an appropriate chunking strategy given document structure, embedding model context length, and the types of queries the agent will face.',
          'Given a described agent task and available data sources, select the context elements required for the agent to correctly scope and execute the task.',
          'Distinguish between pre-inference retrieval (embedding-based, up-front loading) and just-in-time agentic retrieval (tool calls, dynamic Delta table queries) and select the appropriate strategy for a given use case.',
          'Identify which retrieval failure mode is occurring by using MLflow eval logs and UC metadata, and select the Unity Catalog governance action that most directly resolves the failure.',
          'Given a Databricks agent deployment that will retrieve context from a Unity Catalog environment containing both authoritative and derived data assets, design a governance strategy that constrains the agent\'s retrieval space to authoritative sources before deployment.',
        ],
        trackSlugs: ['databricks', 'rag', 'agents', 'data-governance', 'agentic-ai'],
        communityHighlights: [
          'Highest-weight domain at 20% — the largest single section of the exam.',
          'Genie space configuration with Unity Catalog (tables, views, SoL functions, parameterized queries) is heavily emphasized.',
          'Vector Search configuration and RAG pipeline design are core skills — know chunking strategies and embedding model constraints.',
          'Distinction between pre-inference (embedding-based) vs. just-in-time (tool-call) retrieval is explicitly tested.',
          'Unity Catalog metadata quality directly impacts agent retrieval performance — know which metadata fields matter.',
        ],
      },
      {
        id: 'memory-architecture-lakebase-mlflow',
        name: 'Memory Architecture with Lakebase and MLflow',
        weight: 18,
        icon: '🧠',
        objectives: [
          'Given a Databricks agent that is exhibiting degraded performance due to memory type mismatch, identify the mismatch and select the storage configuration that correctly aligns memory type with scope, retrieval pattern, and persistence requirements.',
          'Identify when a Delta-backed state object is required over an in-context scratchpad for an agent operating on a multi-step task.',
          'Given an agent retrieving memories persisted in Lakebase, identify whether Databricks Vector Search or structured query retrieval is the appropriate mechanism for a specified query type.',
          'Given MLflow 3 experiment results across multiple agent runs, identify which context configuration produced the most reliable outcomes on a specified task.',
          'Evaluate the tradeoffs of static retrieval vs. dynamic retrieval from Lakebase for a given agent architecture.',
          'Diagnose risks of over-retrieval (context pollution) and under-retrieval (missing relevant history) in a memory system.',
          'Configure persistent agent memory across sessions using Lakebase-backed durable store.',
          'Given a Databricks agent pipeline that produces accurate but contextually mismatched responses, identify the pipeline stage where user intent should be resolved before context retrieval.',
        ],
        trackSlugs: ['databricks', 'agents', 'agentic-ai', 'mlsys'],
        communityHighlights: [
          'Second-highest domain weight at 18% — Lakebase is a brand-new Databricks product; study it specifically.',
          'Memory type taxonomy (in-context scratchpad vs. Delta-backed durable store) is explicitly tested with scenario-based questions.',
          'MLflow 3 experiment tracking is used to compare agent memory configurations across runs.',
          'Know when to use Vector Search vs. structured Delta table queries for memory retrieval.',
          'Over-retrieval (context pollution) vs. under-retrieval (missing history) is a key diagnostic concept.',
        ],
      },
      {
        id: 'tool-design-mcp-agent-context',
        name: 'Tool Design, MCP, and Agent Context',
        weight: 13,
        icon: '🔧',
        objectives: [
          'Apply the Databricks layered MCP architecture (discovery → planning → execution) to reduce token usage compared to raw tool dumps.',
          'Given two MCP tool descriptions that an agent is consistently confusing, identify the overlap in their descriptions that is causing ambiguous tool selection.',
          'Explain how the Databricks MCP layered architecture uses progressive disclosure to control how much tool information enters the agent context window at each stage, and why this staged approach reduces token consumption compared to loading full tool schemas upfront.',
          'Given an agent with a deep message history where the context window is approaching capacity, evaluate which raw tool outputs are candidates for clearing.',
          'Given a described agent task, identify which tool in a Unity Catalog-registered tool registry is most appropriate based on semantic similarity to the task description.',
          'Given a Databricks agent whose system prompt is overloaded with rarely-invoked capability instructions, identify which capabilities are candidates for packaging as Agent Skills and select the loading strategy that minimizes baseline context cost without harming task success rate.',
        ],
        trackSlugs: ['databricks', 'agents', 'agentic-ai', 'llms'],
        communityHighlights: [
          'MCP (Model Context Protocol) layered architecture (discovery → planning → execution) is a core Databricks-specific concept.',
          'Progressive disclosure of tool schemas is the key mechanism for reducing token consumption in tool-heavy agents.',
          'Agent Skills packaging is a Databricks-specific pattern for lazy-loading rarely-used capabilities.',
          'Tool disambiguation — identifying overlap causing ambiguous tool selection — is scenario-tested.',
          'Unity Catalog tool registry with semantic similarity matching is tested for tool selection.',
        ],
      },
      {
        id: 'context-compression-compaction',
        name: 'Context Compression and Compaction',
        weight: 11,
        icon: '🗜️',
        objectives: [
          'Given a long-running agent task that has been compacted and is now exhibiting downstream coherence failures, identify which category of information was incorrectly discarded during compaction and select the compaction prompt revision that preserves that category without significantly increasing the token cost of the summarized context.',
          'Tune a compaction prompt for a Databricks agent trace: maximize recall first (capture everything relevant), then iterate to improve precision (remove superfluous outputs).',
          "Given a long-running Databricks agent task where context window pressure is building, evaluate whether hard-coded trimming heuristics are sufficient for the task's information relevance pattern, or if it requires a more sophisticated compaction approach.",
          'Given a Databricks agent trace, identify which content is safe to remove during compaction without affecting downstream task execution.',
          'Evaluate the tradeoffs between aggressive compaction (lower token cost, risk of losing subtle context) and conservative compaction (higher fidelity, higher cost).',
        ],
        trackSlugs: ['databricks', 'agents', 'agentic-ai', 'llms'],
        communityHighlights: [
          'Compaction prompt tuning follows a two-phase approach: maximize recall first, then improve precision.',
          'Coherence failures after compaction indicate important information was discarded — know which categories to protect.',
          'Hard-coded trimming heuristics vs. model-based compaction is a key architectural decision tested here.',
          'Aggressive vs. conservative compaction tradeoffs (token cost vs. context fidelity) are scenario-tested.',
          'Safe-to-remove content identification from agent traces requires understanding of downstream task dependencies.',
        ],
      },
      {
        id: 'multi-agent-long-horizon-task-design',
        name: 'Multi-Agent and Long-Horizon Task Design',
        weight: 13,
        icon: '🕸️',
        objectives: [
          'Diagnose failure modes in multi-agent systems caused by insufficient shared context: inconsistent outputs, conflicting decisions, degraded reliability.',
          'Given a multi-agent system where a coordinating agent has decomposed a task and dispatched sub-agents, and the system is now exhibiting downstream failures, diagnose the root cause (i.e., sub-agents receiving individual task messages rather than full agent traces at dispatch time), and select the configuration that resolves the failure without expanding each sub-agent\'s context window.',
          'Given a multi-agent system producing conflicting outputs, identify the context propagation change that would most likely prevent the conflict.',
          "Given a multi-agent Databricks workflow where the orchestrating agent is experiencing context saturation, identify the sub-agent output design change that would most reduce orchestrator context load without compromising task coherence.",
          "Given a multi-agent system design where agent boundaries have been drawn and the resulting architecture is either exhibiting excessive handoff compression overhead or unmanageable context window growth within individual agents, diagnose which boundary placement failure is occurring.",
          "Given a long-running Databricks agent task with documented performance failures, identify which long-horizon strategy mismatch is causing the observed failure, select the replacement strategy most appropriate for the task's dependency structure, and justify the selection by identifying the specific characteristic that makes the original strategy insufficient.",
        ],
        trackSlugs: ['databricks', 'agents', 'agentic-ai', 'llms'],
        communityHighlights: [
          'Sub-agent context propagation is the central challenge — full agent trace vs. individual task message dispatch is explicitly tested.',
          'Orchestrator context saturation and sub-agent output design to reduce orchestrator load are key scenarios.',
          'Agent boundary placement failure modes (excessive handoff compression vs. unmanageable context growth) are tested.',
          'Long-horizon strategy mismatch diagnosis requires understanding task dependency structures.',
          'Multi-agent coherence failures trace back to shared context deficiencies — know how to fix without expanding all sub-agent windows.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // Databricks Certified Associate Developer for Apache Spark
  // ─────────────────────────────────────────────────────────────
  {
    id: 'databricks-spark-developer',
    name: 'Databricks Certified Associate Developer for Apache Spark',
    shortName: 'Spark Associate Dev',
    provider: 'databricks',
    level: 'associate',
    icon: '⚡',
    color: 'spark',
    examUrl: 'https://www.databricks.com/learn/certification/apache-spark-developer-associate',
    studyGuideUrl:
      'https://www.databricks.com/sites/default/files/2025-10/databricks-certified-associate-developer-apache-spark-exam-guide-oct-2025.pdf',
    guideVersion: 'Oct 2025',
    domains: [
      {
        id: 'spark-architecture-components',
        name: 'Apache Spark Architecture and Components',
        weight: 20,
        icon: '🏗️',
        objectives: [
          'Identify advantages and challenges of implementing Apache Spark',
          'Explain core cluster architecture: driver node, worker nodes, executors, CPU cores, and memory',
          'Describe the DataFrame and Dataset API concepts and SparkSession lifecycle',
          'Explain lazy evaluation and the difference between transformations and actions',
          'Describe the execution hierarchy: jobs, stages, tasks',
          'Explain deployment and execution modes: client mode, cluster mode, local mode',
          'Describe fault tolerance mechanisms in Spark',
          'Explain caching, storage levels (MEMORY_ONLY, MEMORY_AND_DISK, etc.), and garbage collection',
          'Describe partitioning, shuffles, and how shuffle-inducing operations work',
          'Identify features of Spark modules: Spark SQL, DataFrames, Pandas API on Spark, Structured Streaming, MLlib',
          'Explain broadcasting and broadcast variables',
        ],
        trackSlugs: ['spark', 'pyspark', 'databricks'],
        communityHighlights: [
          'Lazy evaluation and the transformation vs. action distinction are heavily tested — know exactly when execution triggers',
          'Understanding when shuffles occur (wide vs. narrow transformations) trips up many candidates',
          'Execution hierarchy (jobs → stages → tasks) and how Spark DAG works are frequently examined',
          'Driver vs. executor roles and how memory is allocated between them appear repeatedly',
          'Broadcasting mechanics and when Spark automatically broadcasts small tables is a common question',
        ],
      },
      {
        id: 'spark-sql',
        name: 'Using Spark SQL',
        weight: 20,
        icon: '🗄️',
        objectives: [
          'Utilize common data sources (JDBC, CSV, JSON, Parquet, ORC, Delta, text files) to read and write DataFrames',
          'Execute SQL queries directly on files: ORC, JSON, CSV, text, and Delta files',
          'Understand different save modes: overwrite, append, ignore, errorIfExists',
          'Save data to persistent tables with sorting and partitioning optimization',
          'Register DataFrames as temporary views for SQL querying',
          'Write and execute SQL queries within a Spark session using spark.sql()',
          'Understand schema inference vs. user-defined schemas',
          'Use SQL window functions (rank, row_number, lead, lag, etc.)',
          'Apply Spark SQL aggregate functions',
          'Understand the Catalyst optimizer and query plan optimization',
        ],
        trackSlugs: ['spark', 'pyspark', 'sql', 'databricks'],
        communityHighlights: [
          'SQL joins and window functions (rank, row_number, lead, lag) are heavily drilled with subtle edge cases',
          'Knowing when to use temporary views vs. persistent tables and the trade-offs is commonly tested',
          'Save mode semantics (overwrite vs. append vs. ignore) appear frequently in scenario questions',
          'Reading and writing multiple file formats with correct options (inferSchema, header, etc.) is a key topic',
          'Catalyst optimizer and when it can vs. cannot optimize a query is a differentiating question type',
        ],
      },
      {
        id: 'dataframe-api-applications',
        name: 'Developing Apache Spark DataFrame/DataSet API Applications',
        weight: 30,
        icon: '📊',
        objectives: [
          'Select, rename, add, and drop columns using DataFrame API',
          'Filter rows using boolean conditions and SQL-style expressions',
          'Sort DataFrames (ascending/descending, nulls first/last)',
          'Perform aggregations: count, countDistinct, approxCountDistinct, sum, mean, min, max, summary',
          'Use groupBy, agg, pivot, and rollup operations',
          'Handle missing data: dropna, fillna, replace',
          'Combine DataFrames: inner join, left join, right join, outer join, cross join, broadcast join',
          'Perform union, unionAll, unionByName operations',
          'Explode arrays and work with complex data types (arrays, maps, structs)',
          'Apply string functions (split, concat, substring, upper, lower, trim, regexp_replace)',
          'Apply math and numeric functions',
          'Apply date and timestamp functions including Unix epoch conversions and date component extraction',
          'Create and invoke UDFs (user-defined functions) with and without stateful operators',
          'Describe and use broadcast variables and accumulators',
          'Implement broadcast joins for small table optimization',
          'Read and write DataFrames with explicit schemas',
          'Perform data deduplication using distinct and dropDuplicates',
          'Use collect(), take(), show() and understand implications',
          'Convert between DataFrames, Datasets, and RDDs',
          'Use withColumn, selectExpr, and expr for column transformations',
          'Apply window functions for analytical operations on streaming and batch data',
        ],
        trackSlugs: ['spark', 'pyspark', 'databricks', 'python'],
        communityHighlights: [
          'DataFrame API questions make up 30% of the exam — this is the single most important domain to master thoroughly',
          'Complex joins (broadcast join, cross join, left anti join) with subtle correctness questions appear frequently',
          'UDF creation and when to prefer built-in functions over UDFs for performance is a key differentiator',
          'Window functions (partition by, order by, rows between/range between) require hands-on practice',
          'Handling nulls correctly in filters, joins, and aggregations is a common gotcha in exam questions',
        ],
      },
      {
        id: 'troubleshooting-tuning',
        name: 'Troubleshooting and Tuning',
        weight: 10,
        icon: '🔧',
        objectives: [
          'Implement performance optimization strategies: partitioning, repartitioning, coalescing',
          'Identify and resolve data skew and reduce unnecessary shuffling',
          'Describe Adaptive Query Execution (AQE) and its four major features: dynamic join switching, dynamic partition coalescing, dynamic skew handling, empty relation propagation',
          'Perform logging and monitoring by analyzing driver and executor logs',
          'Diagnose out-of-memory (OOM) errors and resolve executor/driver memory issues',
          'Identify cluster underutilization and overprovisioning issues',
          'Understand and use the Spark UI to diagnose slow stages and tasks',
          'Compare repartition() (full shuffle, can increase/decrease) vs. coalesce() (no full shuffle, only decrease)',
          'Understand caching strategies and when to persist vs. cache vs. unpersist',
          'Tune Spark configuration properties for executor memory, cores, and parallelism',
        ],
        trackSlugs: ['spark', 'pyspark', 'databricks', 'data-reliability'],
        communityHighlights: [
          'AQE (Adaptive Query Execution) — its four features and when it kicks in — is a must-know for tuning questions',
          'Coalesce vs. repartition trade-offs (shuffle behavior, when to use each) appear in multiple question forms',
          'Data skew detection and remediation strategies (salting, broadcast joins, AQE skew handling) are tested',
          'Reading Spark UI — identifying slow stages, shuffle read/write sizes, and spill — appears in scenario questions',
          'OOM errors: distinguishing driver OOM vs. executor OOM and remediation steps is a common exam scenario',
        ],
      },
      {
        id: 'structured-streaming',
        name: 'Structured Streaming',
        weight: 10,
        icon: '🌊',
        objectives: [
          'Explain the Structured Streaming programming model and its relation to batch DataFrames',
          'Describe micro-batch processing and continuous processing modes',
          'Understand exactly-once semantics and fault tolerance via checkpointing',
          'Create streaming DataFrames by reading from sources (Kafka, socket, file, Delta)',
          'Write streaming DataFrames to sinks with output modes: append, complete, update',
          'Perform stateless operations on streaming data: selection, projection, filtering',
          'Apply window-based aggregations on event time (tumbling windows, sliding windows)',
          'Understand event time vs. processing time and when each matters',
          'Implement watermarks for handling late-arriving data',
          'Implement streaming deduplication with and without watermarks',
          'Use trigger options: default micro-batch, fixed interval, once, availableNow',
        ],
        trackSlugs: ['spark', 'pyspark', 'databricks', 'kafka'],
        communityHighlights: [
          'Event time vs. processing time semantics and watermark behavior for late data is heavily tested',
          'Output modes (append vs. complete vs. update) and which operations are valid with each mode trips many candidates',
          'Exactly-once guarantees and how checkpointing enables fault tolerance is a key conceptual question',
          'Window semantics (tumbling vs. sliding, duration vs. slide interval) require solid understanding',
          'Streaming deduplication with watermarks is a newer topic gaining more exam weight',
        ],
      },
      {
        id: 'spark-connect',
        name: 'Using Spark Connect',
        weight: 5,
        icon: '🔌',
        objectives: [
          'Describe Spark Connect architecture and its client-server separation model',
          'Explain the benefits of Spark Connect: stability, upgradability, remote connectivity',
          'Explain deployment mode types in context of Spark Connect: client mode, cluster mode, local mode',
          'Understand how Spark Connect decouples the client from the Spark driver',
          'Describe how Spark Connect enables thin client access to Spark clusters',
        ],
        trackSlugs: ['spark', 'pyspark', 'databricks'],
        communityHighlights: [
          "Spark Connect is a lower-weight domain (5%) — focus on what it is conceptually, not deep implementation details",
          'The key selling point — client-server separation enabling thin clients and stability — is the core exam angle',
          'Deployment modes (client vs. cluster vs. local) in the context of Spark Connect recur across architecture questions',
          'Do not spend excessive study time here; a basic understanding of benefits and architecture is sufficient',
          "Likely tested as 2-3 questions at most — understand the 'why' of Spark Connect over traditional Spark submission",
        ],
      },
      {
        id: 'pandas-api-on-spark',
        name: 'Using Pandas API on Apache Spark',
        weight: 5,
        icon: '🐼',
        objectives: [
          'Explain the advantages of Pandas API on Spark vs. native pandas for large datasets',
          'Create Spark DataFrames from pandas DataFrames and vice versa',
          'Understand the performance implications and when to use Pandas API on Spark vs. PySpark DataFrame API',
          'Create and invoke Pandas UDFs (vectorized UDFs) for distributed pandas DataFrame processing',
          'Understand the different Pandas UDF types: scalar, grouped map, grouped aggregate',
          'Apply Pandas API on Spark for familiar pandas-style operations at scale',
        ],
        trackSlugs: ['spark', 'pyspark', 'databricks', 'python'],
        communityHighlights: [
          'Pandas API on Spark is a lower-weight domain (5%) — know the conceptual differences from native pandas and PySpark',
          'Pandas UDFs (vectorized UDFs) performance advantage over regular Python UDFs is a key testable concept',
          'Conversion between pandas DataFrame and Spark DataFrame (toPandas(), createDataFrame()) is commonly tested',
          'The trade-offs of Pandas API on Spark vs. native PySpark DataFrame API appear in scenario questions',
          "Focus on the 'why use this' angle rather than memorizing every API method",
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // Databricks Certified Data Analyst Associate
  // ─────────────────────────────────────────────────────────────
  {
    id: 'databricks-data-analyst',
    name: 'Databricks Certified Data Analyst Associate',
    shortName: 'DA Associate',
    provider: 'databricks',
    level: 'associate',
    icon: '📊',
    color: 'sql',
    examUrl: 'https://www.databricks.com/learn/certification/data-analyst-associate',
    studyGuideUrl:
      'https://www.databricks.com/sites/default/files/2025-10/databricks-certified-data-analyst-associate-oct-2025.pdf',
    guideVersion: 'Oct-2025',
    domains: [
      {
        id: 'databricks-platform',
        name: 'Understanding the Databricks Data Intelligence Platform',
        weight: 11,
        icon: '🏗️',
        objectives: [
          'Describe core components: Mosaic AI, Delta Live Tables, Lakeflow Jobs, Data Intelligence Engine, Delta Lake, Unity Catalog, and Databricks SQL',
          'Understand the structure of catalogs, schemas, managed and external tables, access controls, views, certified tables, and lineage',
          'Describe the role and features of Databricks Marketplace',
          'Explain the benefits of the Lakehouse architecture versus traditional data warehouses',
          'Describe the relationship between Databricks SQL warehouses and compute resources',
        ],
        trackSlugs: ['databricks', 'sql', 'data-governance'],
        communityHighlights: [
          'Know the full list of platform components by name — Mosaic AI, Lakeflow, Delta Live Tables, etc. appear in conceptual questions',
          'Understand Lakehouse vs. data warehouse tradeoffs and when each is appropriate',
          'Unity Catalog namespace (catalog → schema → table) is foundational and tested across multiple domains',
          'Databricks Marketplace role and Delta Sharing concepts appear in platform overview questions',
          'The 2025 update shifted this from SQL-specialist to a full Data Intelligence Platform credential — expect broader platform questions',
        ],
      },
      {
        id: 'managing-data',
        name: 'Managing Data',
        weight: 8,
        icon: '🗂️',
        objectives: [
          'Use Unity Catalog to discover, query, and manage certified datasets',
          'Use Catalog Explorer to tag a data asset and view its lineage',
          'Perform data cleaning operations on Unity Catalog tables using SQL',
          'Understand the difference between managed and external tables in Unity Catalog',
          'Apply data quality practices including handling duplicates, nulls, and schema validation',
        ],
        trackSlugs: ['databricks', 'sql', 'data-governance'],
        communityHighlights: [
          'Unity Catalog tagging and lineage via Catalog Explorer is a common scenario question',
          'Know the difference between managed vs. external tables and their lifecycle implications',
          'Data cleaning SQL patterns (dedup, null handling) appear as practical scenario questions',
          'Certified datasets concept and how to surface them in the catalog is tested',
          'Understanding Delta Lake as the underlying storage format for managed tables is important',
        ],
      },
      {
        id: 'importing-data',
        name: 'Importing Data',
        weight: 5,
        icon: '📥',
        objectives: [
          'Explain approaches for bringing data into Databricks: S3 ingestion, Delta Sharing for external systems, API-driven data intake, Auto Loader, and Marketplace',
          'Upload data files via the Databricks Workspace UI',
          'Describe when to use Auto Loader versus other ingestion methods',
          'Understand Delta Sharing for sharing data with external systems and partners',
          'Explain the role of Partner Connect for third-party data ingestion',
        ],
        trackSlugs: ['databricks', 'sql'],
        communityHighlights: [
          'Auto Loader vs. COPY INTO is a classic scenario — know when each applies',
          'Delta Sharing purpose and use cases for external data distribution are tested',
          'UI-based file upload is tested conceptually — know its limitations vs. programmatic ingestion',
          "Lowest-weight domain but still covers 2-3 questions — don't skip Partner Connect concepts",
          'API-driven intake and Marketplace as data sources are newer additions to the Oct-2025 guide',
        ],
      },
      {
        id: 'executing-queries',
        name: 'Executing Queries Using Databricks SQL and SQL Warehouses',
        weight: 20,
        icon: '⚡',
        objectives: [
          'Utilize Databricks Assistant in notebooks and SQL Editor for query debugging and generation',
          'Explain the role of SQL Warehouses in query execution and their configuration options',
          'Query cross-system analytics using federated data sources',
          'Create materialized views and streaming views in Databricks SQL',
          'Perform aggregate operations including GROUP BY, ROLLUP, CUBE, and GROUPING SETS',
          'Write join operations (INNER, LEFT, RIGHT, FULL OUTER, CROSS) and set operations (UNION, INTERSECT, EXCEPT)',
          'Perform sorting (ORDER BY) and filtering (WHERE, HAVING) operations',
          'Create managed and external tables from multiple file formats and sources',
          'Use Delta Lake time travel with VERSION AS OF and TIMESTAMP AS OF',
          'Apply window functions (ROW_NUMBER, RANK, LAG, LEAD, PARTITION BY)',
        ],
        trackSlugs: ['databricks', 'sql'],
        communityHighlights: [
          'Highest-weight domain at 20% — SQL proficiency is absolutely essential; practice GROUP BY, ROLLUP, CUBE, GROUPING SETS, and window functions',
          'Materialized view vs. streaming table differences are heavily tested — know when to use each',
          'Delta Lake time travel syntax (VERSION AS OF, TIMESTAMP AS OF) appears frequently',
          'Databricks Assistant is new to the Oct-2025 guide — expect questions on its capabilities for debugging and query generation',
          'SQL Warehouse types (Serverless, Pro, Classic) and their use-case tradeoffs are tested',
        ],
      },
      {
        id: 'analyzing-queries',
        name: 'Analyzing Queries',
        weight: 15,
        icon: '🔍',
        objectives: [
          'Understand Photon features and performance benefits for query acceleration',
          'Identify poorly performing queries using Query Insights in the Databricks SQL UI',
          'Utilize Delta Lake for auditing, history, and time travel queries',
          'Apply query history and result caching to improve performance',
          'Apply Liquid Clustering as an optimization technique and understand when it replaces partitioning',
          'Fix and debug queries to achieve desired results',
          'Analyze query execution plans and interpret query profiles',
          'Understand the impact of Z-ordering vs. Liquid Clustering on query performance',
        ],
        trackSlugs: ['databricks', 'sql'],
        communityHighlights: [
          'Liquid Clustering vs. partitioning vs. Z-ordering is a high-frequency question — Liquid Clustering is the modern default for most scenarios',
          'Query Insights UI navigation and interpreting slow query indicators is tested with scenario questions',
          'Photon acceleration benefits and which workloads it helps are commonly asked',
          'Delta Lake DESCRIBE HISTORY and audit log usage appear in scenario questions',
          'Result caching behavior (when cache is invalidated, how to force refresh) is a common gotcha',
        ],
      },
      {
        id: 'dashboards-visualizations',
        name: 'Creating Dashboards and Visualizations',
        weight: 16,
        icon: '📊',
        objectives: [
          'Build AI/BI Dashboards with multi-tab layouts and widgets',
          'Create visualizations in notebooks and SQL Editor (bar, line, pie, heatmap, counter, etc.)',
          'Configure SQL query parameters and use them in dashboard widgets',
          'Configure permissions and sharing settings for dashboards',
          'Schedule automatic dashboard refresh and understand permission requirements for scheduled runs',
          'Configure alerts with threshold conditions and notification channels',
          'Select effective visualization types for different data shapes and analytical goals',
          'Embed and publish dashboards for stakeholder consumption',
        ],
        trackSlugs: ['databricks', 'sql', 'bi'],
        communityHighlights: [
          'Second highest domain at 16% — must have hands-on dashboard experience; questions are very UI-specific',
          'Alert configuration (threshold types, notification channels, frequency) is a common scenario question',
          'Dashboard refresh permissions — knowing that a service principal or owner must be set for scheduled refresh is a known gotcha',
          'Parameter configuration in SQL queries and linking to dashboard filters is heavily tested',
          'Visualization type selection (when to use counter vs. bar vs. time-series) appears as scenario questions',
        ],
      },
      {
        id: 'genie-spaces',
        name: 'Developing AI/BI Genie Spaces',
        weight: 12,
        icon: '🧞',
        objectives: [
          'Describe the purpose and key features of AI/BI Genie spaces for natural language data querying',
          'Create Genie spaces with sample questions and domain-specific instructions',
          'Assign permissions and distribute Genie spaces to end users',
          'Optimize Genie spaces through user feedback, trusted assets, and curated questions',
          'Understand how Genie translates natural language questions into SQL',
          'Configure Genie space data sources and context instructions',
        ],
        trackSlugs: ['databricks', 'sql', 'llms'],
        communityHighlights: [
          "Newest domain in the Oct-2025 update — many candidates haven't used it; hands-on practice in a real workspace is critical",
          'Genie space configuration (domain instructions, sample questions, trusted assets) is directly tested',
          'Permissions model for Genie spaces (who can use vs. who can edit) appears in scenario questions',
          'Understanding how Genie differs from a standard SQL dashboard is a conceptual question type',
          'Optimizing Genie through feedback loops and trusted assets is a higher-order objective that distinguishes exam takers',
        ],
      },
      {
        id: 'data-modeling',
        name: 'Data Modeling with Databricks SQL',
        weight: 5,
        icon: '🧩',
        objectives: [
          'Apply star schema and snowflake schema modeling patterns in Databricks SQL',
          'Understand data vault schema concepts and when to apply them',
          'Align data models with Medallion Architecture (Bronze, Silver, Gold layers)',
          'Understand the role of fact tables, dimension tables, and their relationships',
          'Apply SCD (Slowly Changing Dimensions) concepts where relevant',
        ],
        trackSlugs: ['databricks', 'sql', 'modeling'],
        communityHighlights: [
          'Low weight at 5% but Medallion Architecture (Bronze/Silver/Gold) is foundational and appears in multiple domains',
          'Star schema vs. snowflake schema tradeoffs are conceptual questions — know the denormalization benefit',
          'Data vault is mentioned in the objectives but rarely appears in practice questions — prioritize star/snowflake',
          'Questions often frame modeling in the context of Databricks SQL views and materialized views',
          'Understanding which Medallion layer supports which query patterns (Gold = reporting) is tested',
        ],
      },
      {
        id: 'securing-data',
        name: 'Securing Data',
        weight: 8,
        icon: '🔐',
        objectives: [
          'Use Unity Catalog roles (catalog owner, schema owner, table owner, data reader, etc.) and sharing settings',
          'Understand the 3-level namespace structure (catalog → schema → table/view) and its security implications',
          'Apply data security best practices including row-level security and column masking',
          'Configure access controls for tables, views, and external locations',
          'Understand external location and storage credential concepts in Unity Catalog',
          'Apply data sharing governance with Delta Sharing',
        ],
        trackSlugs: ['databricks', 'data-governance', 'sql'],
        communityHighlights: [
          'Unity Catalog 3-level namespace and privilege inheritance is foundational — every security question builds on this',
          'Row-level security via dynamic views is a commonly tested advanced security pattern',
          'Column masking for PII data protection appears in scenario questions',
          'External location vs. storage credential concepts distinguish intermediate from advanced understanding',
          'Delta Sharing governance and recipient management appears in security context questions',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // Databricks Certified Machine Learning Associate
  // ─────────────────────────────────────────────────────────────
  {
    id: 'databricks-ml-associate',
    name: 'Databricks Certified Machine Learning Associate',
    shortName: 'ML Associate',
    provider: 'databricks',
    level: 'associate',
    icon: '🔬',
    color: 'dbt',
    examUrl: 'https://www.databricks.com/learn/certification/machine-learning-associate',
    studyGuideUrl:
      'https://www.databricks.com/sites/default/files/2024-10/databricks-certified-machine-learning-associate-exam-guide-interrim.pdf',
    guideVersion: '2025-interim',
    domains: [
      {
        id: 'databricks-machine-learning',
        name: 'Databricks Machine Learning',
        weight: 38,
        icon: '🧠',
        objectives: [
          'Understand ML runtimes and their pre-installed libraries/advantages over standard runtimes',
          'Explain AutoML functionality: automated model selection, feature selection, and hyperparameter tuning',
          'Identify what AutoML automatically handles (e.g., imputation, encoding) vs. what requires manual configuration',
          'Create and manage Unity Catalog Feature Store tables (account-level vs. workspace-level)',
          'Distinguish online vs. offline feature tables and their use cases',
          'Write and read features from the Feature Store using FeatureStoreClient',
          'Train models with features sourced from the Feature Store',
          'Score/inference models using Feature Store lookups',
          'Use MLflow Tracking: mlflow.start_run(), mlflow.log_metric(), mlflow.log_param(), mlflow.log_artifact()',
          'Enable and configure mlflow.autolog() for automatic logging',
          'Register models using MLflow Client API in Unity Catalog registry',
          'Understand Model Registry lifecycle stages: None → Staging → Production → Archived',
          'Use model aliases and tags in the Unity Catalog-based Model Registry',
          'Identify information visible in the MLflow UI (runs, experiments, metrics, artifacts)',
          'Understand Databricks cluster types (Standard vs. Single-node) for ML workloads',
          'Use Git integration with Databricks Repos for ML project versioning',
        ],
        trackSlugs: ['databricks', 'mlsys', 'modeling'],
        communityHighlights: [
          'This is an API-level test, not conceptual — know exact function names and parameter behaviors for MLflow',
          'Model Registry stage transitions are heavily tested: know the full lifecycle None → Staging → Production → Archived',
          'Unity Catalog Feature Store is a major challenge area — understand account-level vs workspace-level tables and online vs offline stores',
          'AutoML questions focus on what it automates (imputation, encoding) vs. what still requires manual intervention',
          'mlflow.autolog() vs manual logging distinction appears frequently — know when each is appropriate',
        ],
      },
      {
        id: 'ml-workflows',
        name: 'ML Workflows',
        weight: 19,
        icon: '🔄',
        objectives: [
          'Compute summary statistics on Spark DataFrames (mean, median, standard deviation, percentiles)',
          'Identify and remove outliers using statistical methods (standard deviation thresholds, IQR)',
          'Visualize feature distributions for categorical and continuous data',
          'Handle missing values using imputation strategies: mean, median, mode imputation',
          'Perform feature engineering: one-hot encoding for categorical variables',
          'Apply log transformations to address skewed distributions',
          'Implement feature scaling (normalization, standardization) using Spark ML transformers',
          'Split datasets appropriately for training, validation, and test sets',
          'Understand time-series specific cross-validation (rolling/walk-forward validation) to preserve temporal order',
          "Apply Hyperopt's fmin() function for hyperparameter search",
          'Configure hyperparameter search spaces (hp.choice, hp.uniform, hp.loguniform)',
          'Distinguish between random search and Bayesian optimization strategies',
          'Understand cross-validation (CrossValidator) vs. TrainValidationSplit trade-offs',
          'Calculate total model evaluations in grid search with k-fold CV (grid size × k folds)',
          'Schedule ML jobs using Databricks Jobs and Delta Live Tables',
        ],
        trackSlugs: ['databricks', 'python', 'mlsys', 'modeling', 'statistics'],
        communityHighlights: [
          'Hyperparameter tuning calculations are critical — know exactly how many models are trained in grid search + k-fold CV combinations',
          'Cross-validation vs. TrainValidationSplit distinctions are heavily tested',
          'Time-series cross-validation (rolling validation) is a common gotcha — must preserve temporal order',
          'Feature engineering questions often focus on when to use one-hot encoding vs. other encoding methods',
          'Imputation strategy selection (mean vs. median vs. mode) based on data distribution is a recurring topic',
        ],
      },
      {
        id: 'model-development',
        name: 'Model Development',
        weight: 31,
        icon: '⚙️',
        objectives: [
          'Select appropriate algorithms for classification, regression, and clustering tasks',
          'Understand when to use linear vs. tree-based vs. ensemble models',
          'Address class imbalance using oversampling (SMOTE), undersampling, or cost-sensitive learning',
          'Distinguish Estimators vs. Transformers in Spark ML Pipeline API',
          'Build end-to-end ML pipelines using Pipeline, PipelineModel, and ParamGridBuilder',
          'Use Spark ML distributed algorithms (LogisticRegression, RandomForest, GBTClassifier, etc.)',
          'Apply single-node frameworks (scikit-learn) vs. distributed Spark ML — know when to use each',
          'Use pandas UDFs (Pandas User-Defined Functions) to apply single-node models across Spark partitions',
          'Leverage Pandas API on Spark for familiar pandas syntax at scale',
          'Evaluate classification models: precision, recall, F1 score, log loss, ROC-AUC',
          'Evaluate regression models: RMSE, MAE, R-squared (R²)',
          'Interpret confusion matrices and derive metrics from them',
          'Understand bias-variance tradeoff and how model complexity affects it',
          'Identify overfitting vs. underfitting and apply regularization (L1/L2)',
          'Extract and interpret feature importance from tree-based models',
          'Use Hyperopt with SparkTrials for distributed hyperparameter tuning',
          'Understand early stopping and convergence criteria for iterative models',
        ],
        trackSlugs: ['databricks', 'python', 'pyspark', 'mlsys', 'modeling', 'statistics', 'spark'],
        communityHighlights: [
          'This is the heaviest domain (31%) — prioritize it; model evaluation metrics and pipeline API are most tested',
          'Spark ML Pipeline API (Estimator/Transformer distinction) is a major focus — know the difference cold',
          'Distributed Spark ML vs. single-node scikit-learn trade-offs appear frequently; know when pandas UDFs are the right bridge',
          'Class imbalance handling strategies are regularly tested — know oversampling vs. undersampling vs. cost-sensitive approaches',
          'Evaluation metric selection for multi-class classification (F1 macro vs. weighted) is a common trap question',
        ],
      },
      {
        id: 'model-deployment',
        name: 'Model Deployment',
        weight: 12,
        icon: '🚀',
        objectives: [
          'Identify differences and advantages of batch, real-time (online), and streaming inference',
          'Choose the appropriate serving approach based on latency and throughput requirements',
          'Deploy models as REST API endpoints using Databricks Model Serving',
          'Understand how to query a deployed model endpoint via REST API',
          'Deploy custom model flavors and pyfunc models to serving endpoints',
          'Implement A/B testing and canary deployment strategies for model rollouts',
          'Use Delta Live Tables (DLT) for streaming inference pipelines',
          'Monitor deployed models for data drift using statistical tests (PSI, JS divergence, Wasserstein distance)',
          'Understand model versioning in deployment and how to promote/archive versions',
          'Distinguish between Champion/Challenger model patterns',
          'Understand the role of Unity Catalog in governing deployed model versions',
        ],
        trackSlugs: ['databricks', 'mlsys', 'modeling', 'data-reliability'],
        communityHighlights: [
          'Batch vs. real-time vs. streaming inference trade-offs are the core of this domain — know the latency/cost profiles',
          'Model Serving REST endpoint deployment and querying syntax appears on the exam',
          'Drift detection metrics (PSI, Wasserstein distance) are tested — know what each measures',
          'A/B testing and canary deployment concepts are included despite domain\'s smaller weight',
          'Delta Live Tables for streaming inference is a newer addition and community members flag it as a growing test topic',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // Databricks Certified Machine Learning Professional
  // ─────────────────────────────────────────────────────────────
  {
    id: 'databricks-ml-professional',
    name: 'Databricks Certified Machine Learning Professional',
    shortName: 'ML Pro',
    provider: 'databricks',
    level: 'professional',
    icon: '🔬',
    color: 'dbt',
    examUrl: 'https://www.databricks.com/learn/certification/machine-learning-professional',
    studyGuideUrl:
      'https://files.training.databricks.com/static/docs/databricks-certified-machine-learning-professional-exam-guide.pdf',
    guideVersion: 'v3.0 (September 2025)',
    domains: [
      {
        id: 'model-development',
        name: 'Model Development Using Spark ML',
        weight: 44,
        icon: '🧪',
        objectives: [
          'Identify when SparkML is recommended based on data size, model type, and use case',
          'Construct ML pipelines using SparkML with appropriate stages',
          'Apply appropriate estimators and transformers for specific use cases',
          'Tune SparkML models using MLlib cross-validation and parameter grids',
          'Evaluate SparkML models using appropriate metrics',
          'Score SparkML models for batch or streaming inference scenarios',
          'Select between SparkML and single-node models for different inference types',
          'Scale distributed training using pandas Function APIs and pandas UDFs',
          'Perform distributed hyperparameter tuning using Optuna integrated with MLflow',
          'Perform distributed hyperparameter tuning using Ray',
          'Evaluate trade-offs between vertical and horizontal scaling strategies',
          'Evaluate and select parallelization strategies (model parallelism vs. data parallelism)',
          'Compare Ray and Spark for distributing ML workloads',
          'Use Pandas Function API for group-specific model training and inference',
          'Utilize nested MLflow runs for tracking complex experiments',
          'Log custom metrics, parameters, and artifacts programmatically with MLflow',
          'Create custom model objects using real-time feature engineering with pyfunc',
          'Ensure point-in-time correctness in Feature Store feature lookups to prevent data leakage',
          'Build automated feature computation pipelines using the FeatureEngineering client',
          'Configure online tables for low-latency feature serving applications',
          'Design scalable solutions for ingesting streaming data to generate features in real time',
          'Develop on-demand features for consistency between training and production',
        ],
        trackSlugs: ['databricks', 'spark', 'pyspark', 'mlsys', 'modeling', 'python'],
        communityHighlights: [
          'SparkML pipeline construction and estimator/transformer selection are heavily tested — know when to use SparkML vs single-node scikit-learn',
          'Distributed hyperparameter tuning with Optuna and Ray is a new 2025 addition; expect multiple questions on comparing Ray vs Spark for ML workloads',
          'Feature Store point-in-time correctness is critical — questions test understanding of data leakage prevention and online table configuration',
          'MLflow nested runs and custom pyfunc model objects appear in scenario-based questions requiring practical experience',
          'Pandas Function API for group-specific model training (e.g., one model per customer segment) is a common scenario',
        ],
      },
      {
        id: 'mlops',
        name: 'MLOps',
        weight: 44,
        icon: '⚙️',
        objectives: [
          'Describe and implement model lifecycle pipeline architecture end-to-end',
          'Map Databricks platform features to model lifecycle management activities',
          'Implement unit tests for notebook functions and ML pipeline components',
          'Identify appropriate testing types across dev, staging, and prod environment stages',
          'Design integration tests for end-to-end ML systems',
          'Compare benefits and challenges of different test organization approaches',
          'Design and implement scalable ML environments using Databricks best practices',
          'Define and configure Databricks ML assets using Databricks Asset Bundles (DABs)',
          'Implement automated retraining workflows triggered by data drift detection or performance degradation alerts',
          'Develop strategy for selecting top-performing models during automated retraining cycles',
          'Apply statistical tests to detect numerical data drift (KS test, Wasserstein distance, Mann-Whitney)',
          'Apply statistical tests to detect categorical data drift (Chi-squared test, Jensen-Shannon divergence, PSI)',
          'Identify data table types and monitoring features appropriate for specific use cases',
          'Build monitors for snapshot tables, time series tables, or inference tables using Lakehouse Monitoring',
          'Identify key components of a Lakehouse Monitoring pipeline',
          'Design and configure alerting mechanisms for drift threshold violations',
          'Detect data drift by comparing feature distributions to baseline reference windows',
          'Evaluate model performance trends using inference tables',
          'Define custom metrics in Lakehouse Monitoring tables',
          'Evaluate metrics by data granularity and feature slicing',
          'Monitor endpoint health and infrastructure metrics for model serving',
        ],
        trackSlugs: ['databricks', 'mlsys', 'modeling', 'python', 'data-reliability'],
        communityHighlights: [
          'Lakehouse Monitoring is the single most tested sub-domain (10 objectives) — master drift detection, inference tables, alerting via SQL alerts + webhooks + Databricks Jobs',
          'Databricks Asset Bundles (DABs) replaced legacy Databricks CLI patterns; know how to define model serving endpoints and MLflow experiments as code',
          'The monitoring→alert→webhook→automated retraining job pipeline appears in multiple questions; understand the full automation chain',
          'PSI for categorical drift and KS test for numerical drift are the go-to metrics — know which to apply and why',
          'Integration testing across dev/staging/prod stages and model validation gates are scenario-heavy; exam tests judgment not just definitions',
        ],
      },
      {
        id: 'model-deployment',
        name: 'Model Deployment',
        weight: 12,
        icon: '🚀',
        objectives: [
          'Compare deployment strategies including blue-green and canary for high-traffic production applications',
          'Implement model rollout strategy using Databricks Model Serving endpoints',
          'Register custom PyFunc models and artifacts in Unity Catalog',
          'Query custom deployed models via REST API or MLflow Deployments SDK',
          'Deploy custom model objects using MLflow deployments, REST API, or Databricks UI',
          'Select appropriate deployment paradigm (batch, streaming, real-time) based on latency and throughput requirements',
          'Score batch predictions using spark_udf and load_model patterns',
          'Implement streaming inference pipelines using Structured Streaming',
          'Configure model serving endpoint traffic splitting for A/B testing and shadow deployments',
          'Integrate Feature Store with model serving for online feature retrieval',
        ],
        trackSlugs: ['databricks', 'mlsys', 'spark', 'python'],
        communityHighlights: [
          'Only 12% of exam weight but questions tend to be high-complexity scenario-based; know blue-green vs canary vs shadow vs A/B trade-offs cold',
          'Custom PyFunc model registration and REST API querying are the most common deployment sub-topics',
          'Batch deployment with spark_udf is tested alongside streaming inference — know when each paradigm fits',
          'Unity Catalog model aliases replaced legacy MLflow Registry stages (Staging/Production) — use aliases in 2025 exam answers',
          'Model serving endpoint configuration including traffic routing and canary rollout percentage is regularly tested',
        ],
      },
    ],
  },
];

export function certById(id: string): CertDef | undefined {
  return CERTS.find((c) => c.id === id);
}

export function certTotalCards(_certId: string): number {
  return 0;
}
